using Godot;
using System.Collections.Generic;

namespace UnturnedGodot.Testing
{
    // THE HELD ITEM'S PARTS MUST MATCH THE PATHS ITS CLIPS ADDRESS (strawberry 2026-09-10: "the chip bag is glued
    // to the right hand" -> "now its.. invsibile?").
    //
    // Three attempts at this shipped broken, and every one of them failed the same way: the clip's tracks did not
    // resolve, Godot logged a warning nobody was reading, and the item either sat frozen or vanished entirely --
    // because Bone_1..Bone_4 rest at scale 0.001 and ONLY the clip scales them up, so an unresolved track is not a
    // missing animation, it is a missing object.
    //
    // What is at risk is the AGREEMENT BETWEEN TWO FILES that are generated by two different tools: the clips say
    // which names they drive (consumable_animparts.tsv, from the animation curves) and the rip says which nodes
    // exist (<item>_parts.tsv, from the prefab hierarchy). Neither file can be checked against itself -- both are
    // internally consistent while disagreeing with each other, which is exactly the state that shipped. So this
    // reads both and cross-references them, and asserts nothing that either file alone could satisfy.
    //
    // Deliberately NOT a render: a render of this shows a chip bag, and a chip bag is what it showed while wrong.
    public sealed class HeldPartHierarchyTests : GameTest
    {
        public override string Name => "viewmodel.held_part_hierarchy";

        static List<string[]> Rows(string path)
        {
            var outp = new List<string[]>();
            using var f = Godot.FileAccess.Open(path, Godot.FileAccess.ModeFlags.Read);
            if (f == null) return outp;
            while (!f.EofReached())
            {
                string ln = f.GetLine();
                if (!string.IsNullOrWhiteSpace(ln)) outp.Add(ln.Split('\t'));
            }
            return outp;
        }

        public override IEnumerable<Step> Run()
        {
            // clips -> the part names each item's Equip/Use actually drive
            var animParts = new Dictionary<string, string[]>();
            foreach (var c in Rows("res://content/consumable_animparts.tsv"))
                if (c.Length >= 2) animParts[c[0].Trim()] = c[1].Split(',');
            T.Check($"consumable_animparts.tsv lists animated parts ({animParts.Count} items)", animParts.Count > 50);

            // clips -> hook side, which decides which hand the whole assembly hangs off
            var hook = new Dictionary<string, string>();
            foreach (var c in Rows("res://content/consumable_anims.tsv"))
                if (c.Length >= 5) hook[c[0].Trim()] = c[4].Trim();
            int lefties = 0;
            foreach (var kv in hook) if (kv.Value == "Left") lefties++;
            // The bug was hanging every consumable off Right_Hook. If this ever reads 0 the hook column has been
            // dropped from the rip and the left-handed items are silently back on the wrong hand.
            T.Check($"some consumables are LEFT-hook items ({lefties} of {hook.Count})", lefties > 0);
            T.Check("bag_chips specifically is a left-hook item",
                hook.TryGetValue("bag_chips", out var bch) && bch == "Left");

            int checkedItems = 0, missingParts = 0, badParent = 0, noDraw = 0, undrawnMeshed = 0;
            string firstMissing = null, firstBadParent = null, firstNoDraw = null;

            foreach (var kv in animParts)
            {
                string tsv = $"res://content/{kv.Key}_parts.tsv";
                if (!Godot.FileAccess.FileExists(tsv)) continue;
                var rows = Rows(tsv);
                if (rows.Count == 0) continue;
                checkedItems++;

                var seen = new HashSet<string>();
                int roots = 0, drawn = 0;
                foreach (var r in rows)
                {
                    if (r.Length < 7) { badParent++; firstBadParent ??= $"{kv.Key}: row '{r[0]}' has {r.Length} columns"; continue; }
                    // A parent must already have been emitted. The game builds the tree in ONE pass and drops any
                    // row whose parent it has not created yet, so file order is load-bearing, not cosmetic.
                    if (r[5] == "-") roots++;
                    else if (!seen.Contains(r[5])) { badParent++; firstBadParent ??= $"{kv.Key}: '{r[0]}' parent '{r[5]}' comes later"; }
                    seen.Add(r[0]);
                    if (r[6] == "1") drawn++;
                    else if (r[1] != "-") undrawnMeshed++;
                }
                if (roots != 1) { badParent++; firstBadParent ??= $"{kv.Key}: {roots} rows have no parent, want exactly 1"; }
                if (!seen.Contains("Item_Root")) { badParent++; firstBadParent ??= $"{kv.Key}: no Item_Root row"; }
                // Nothing drawn = the invisible bug, exactly as reported.
                if (drawn == 0) { noDraw++; firstNoDraw ??= kv.Key; }

                // ⭐ THE ONE THAT MATTERS. Every name the clips drive must exist as a node. This is the assertion
                // that fails on "AnimationMixer: couldn't resolve track", and it fails HERE instead of in a warning
                // stream during play.
                foreach (var p in kv.Value)
                {
                    string nm = p.Trim();
                    if (nm.Length > 0 && !seen.Contains(nm)) { missingParts++; firstMissing ??= $"{kv.Key}/{nm}"; }
                }
            }

            T.Check($"cross-checked a real number of items ({checkedItems})", checkedItems > 50);
            T.Check($"every animated part name exists as a node ({missingParts} missing{(firstMissing != null ? ", first " + firstMissing : "")})", missingParts == 0);
            T.Check($"every part's parent is emitted before it, one root each ({badParent} bad{(firstBadParent != null ? ", first " + firstBadParent : "")})", badParent == 0);
            T.Check($"no item builds with nothing visible ({noDraw} blank{(firstNoDraw != null ? ", first " + firstNoDraw : "")})", noDraw == 0);
            // CONTROL. Without this the draw flag could be all-1s -- every mesh drawn, LOD copies stacked on the
            // parts they duplicate -- and the "nothing blank" check above would still pass happily.
            T.Check($"...and the draw flag actually excludes something ({undrawnMeshed} meshed parts held back as LODs)", undrawnMeshed > 0);
            yield break;
        }
    }
}
