using Godot;
using System.Collections.Generic;

namespace UnturnedGodot.Testing
{
    // THE RECOIL PATTERN'S SHAPE. Pure GunDef math, which had no coverage at all until strawberry playtested the
    // M249 and reported the part of the curve nobody had ever asserted on.
    //
    // strawberry 2026-08-15: "dragonfang need more vertical during its proc still, no more in the designated
    // pattern, just the proc." Two claims in one sentence, and they pull against each other -- the M249's rounds
    // past node 20 are generated by the same PatternPlateau term that has to leave rounds 1-20 untouched. So the
    // checks below are written as COMPARISONS BETWEEN TWO LIVE GunDefs differing in exactly the plateau knobs,
    // never against numbers I wrote down. A hardcoded "vertical at round 30 should be 42.77" is a mirror of the
    // formula it is checking: it passes whenever my arithmetic agrees with itself, including when the arithmetic
    // answers the wrong question.
    public sealed class RecoilPatternTests : GameTest
    {
        public override string Name => "gun.recoil_pattern";
        public override double TimeoutSimSeconds => 20;

        static GunDef Def(string gun) =>
            GunDef.FromDatText(System.IO.File.ReadAllText(ProjectSettings.GlobalizePath("res://content/") + gun + ".dat"));

        public override IEnumerable<Step> Run()
        {
            var df = Def("dragonfang");

            // ---- 1. the belt-fed gun declares a proc phase at all
            T.Check($"the dragonfang declares a plateau ({df.PatternPlateau} deg over span {df.PatternPlateauSpan})",
                df.PatternPlateau > 0f && df.PatternPlateauSpan > 0f && df.PatternNodes > 0);

            // The OLD tuning, rebuilt field-for-field from the live def so only the two plateau knobs differ.
            // This is the control: every other term -- climb, exponent, drift, sway, wiggle -- is shared, so any
            // difference measured below is attributable to the change and to nothing else.
            var old = Def("dragonfang");
            old.PatternPlateau = 27.6f; old.PatternPlateauSpan = 0.93f;

            // ---- 2. THE CONSTRAINT: "no more in the designated pattern". Rounds 1..PatternNodes must be
            // BIT-IDENTICAL between the two, or the tuning leaked into the part she signed off on.
            int n = df.PatternNodes;
            float worstIn = 0f; int worstInShot = 0;
            for (int s = 1; s <= n; s++)
            {
                float d = Mathf.Abs(df.PatternAt(s).V - old.PatternAt(s).V);
                if (d > worstIn) { worstIn = d; worstInShot = s; }
            }
            T.Check($"rounds 1-{n} are untouched by the proc change (worst {worstIn:0.######} deg at round {worstInShot})",
                worstIn < 0.0001f);

            // ---- 3. THE ASK: more vertical in the proc. Per-shot KICK, not the cumulative total -- a bigger
            // total reached at the same slack rate is not what "more vertical during its proc" means, and the
            // cumulative version of this check passes on a curve that adds all its height in one spike.
            float Kick(GunDef g, int shot) => g.PatternAt(shot).V - g.PatternAt(shot - 1).V;
            foreach (int s in new[] { n + 1, 30, 50, 100 })
            {
                float now = Kick(df, s), was = Kick(old, s);
                T.Check($"round {s} kicks harder than it used to ({now:0.###} vs {was:0.###} deg)", now > was * 1.15f);
            }
            // ...and it must not go slack deep in the belt, which is the actual complaint: the old curve was not
            // weak at the handover (1.45 deg on round 21), it DIED -- 0.02 deg by round 100, so the rounds meant
            // to be unholdable were the easiest in the magazine.
            T.Check($"the proc still climbs at round 100 ({Kick(df, 100):0.###} deg/round)", Kick(df, 100) > 0.1f);

            // ---- 4. strawberry's standing rule, over the WHOLE belt: "recoil should never go down".
            float prev = -1f; int fellAt = 0;
            for (int s = 1; s <= df.AmmoMax; s++)
            {
                float v = df.PatternAt(s).V;
                if (v < prev - 0.0001f && fellAt == 0) fellAt = s;
                prev = v;
            }
            T.Check($"vertical never decreases across a full {df.AmmoMax}-round belt" + (fellAt > 0 ? $" (fell at round {fellAt})" : ""),
                fellAt == 0);

            // ---- 5. BOUNDED. _pitchDeg clamps at +-89, and a pattern that reaches it stops being a pattern --
            // the last rounds of the belt would all land on the clamp and feel like no recoil at all, which is
            // the exact symptom being fixed. Headroom checked at the real Ammo_Max, not at some sampled round.
            float top = df.PatternAt(df.AmmoMax).V;
            T.Check($"a full belt stays under the pitch clamp ({top:0.#} deg at round {df.AmmoMax}, clamp 89)", top < 85f);

            // ---- 6. NOT EVERYONE. The plateau is a belt-fed concession; a rifle must have no proc phase at all,
            // or this quietly re-tuned every gun rather than the one she asked about.
            var ef = Def("eaglefire");
            T.Check($"the eaglefire has no proc phase (plateau {ef.PatternPlateau})", Mathf.IsZeroApprox(ef.PatternPlateau));
            T.Check($"...so its pattern is flat past its last node ({ef.PatternAt(ef.PatternNodes + 40).V:0.##} == {ef.PatternAt(ef.PatternNodes).V:0.##})",
                Mathf.IsEqualApprox(ef.PatternAt(ef.PatternNodes + 40).V, ef.PatternAt(ef.PatternNodes).V));

            yield break;
        }
    }
}
