#!/usr/bin/env python3
"""Rebuild closed component meshes and the measured spec; +Y up, front -Z."""
import math
from pathlib import Path
from PIL import Image
from measure_vehicles import ROOT, CONTENT, obj
from measure_car_trailer import measurements, design, TOW_CARS
from build_wagon import Mesh

COLORS = [(151,159,158,255),(88,111,87,255),(135,105,69,255),(46,49,48,255),
          (142,32,32,255),(225,157,49,255),(201,204,198,255),(22,25,25,255)]

def uv(color): return ((color%4+.5)/4,1-(color//4+.5)/2)

class Model(Mesh):
    def __init__(self):
        super().__init__(); self.groups=[]
    def component(self,name): self.groups.append((len(self.f),name))
    def polygon(self,ps,color):
        for i in range(1,len(ps)-1): self.tri([ps[0],ps[i],ps[i+1]],[uv(color)]*3)
    def prism(self,low,high,color):
        # Two corresponding rings. Wind each face away from the component centre.
        c=tuple(sum(p[i] for p in low+high)/len(low+high) for i in range(3))
        for ps in [low,list(reversed(high))]+[[low[i],high[i],high[(i+1)%len(low)],low[(i+1)%len(low)]] for i in range(len(low))]:
            a,b,d=ps[:3]; u=[b[i]-a[i] for i in range(3)];v=[d[i]-a[i] for i in range(3)]
            n=(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])
            if sum(n[i]*(a[i]-c[i]) for i in range(3))<0: ps=list(reversed(ps))
            self.polygon(ps,color)
    def box(self,name,lo,hi,color=0):
        self.component(name)
        self.prism([(lo[0],lo[1],lo[2]),(hi[0],lo[1],lo[2]),(hi[0],lo[1],hi[2]),(lo[0],lo[1],hi[2])],
                   [(lo[0],hi[1],lo[2]),(hi[0],hi[1],lo[2]),(hi[0],hi[1],hi[2]),(lo[0],hi[1],hi[2])],color)
    def beam(self,name,a,b,width,height,color=0):
        self.component(name)
        dx,dz=b[0]-a[0],b[2]-a[2];l=math.hypot(dx,dz); nx,nz=dz/l*width/2,-dx/l*width/2
        rings=[[(p[0]-nx,p[1]-height/2,p[2]-nz),(p[0]+nx,p[1]-height/2,p[2]+nz),
                (p[0]+nx,p[1]+height/2,p[2]+nz),(p[0]-nx,p[1]+height/2,p[2]-nz)] for p in [a,b]]
        self.prism(*rings,color)
    def save(self,name):
        self.write(name,weld_positions=True)
        p=CONTENT/name;lines=p.read_text().splitlines();out=[];face=0;groups=dict(self.groups)
        for line in lines:
            if line.startswith('# Generated'): line='# Generated by tools/build_car_trailer.py; metres, +Y up, front -Z.'
            if line.startswith('g '): continue
            if line.startswith('f '):
                if face in groups:out.append('g '+groups[face])
                face+=1
            out.append(line)
        p.write_text('\n'.join(out)+'\n')


def sedan_lamps(rear_z, centre_y):
    """The SEDAN's tail lights, moved -- not a pair of boxes shaped like them.

    strawberry: "the tail lights should be off the sedan". Parts are drawn with a flat SolidMat, so
    only the geometry travels; the mesh keeps its 56 verts / 20 tris and its exact 2.2269 x 0.3291 x
    0.1899 section, and is translated so its front face meets the trailer's rear and its lenses centre
    on the tailgate. X is untouched: at +/-1.1135 they already sit inside a 2.462 deck, which is why
    they fit a trailer at all. UVs are re-pointed at the trailer palette's own red -- itself now the
    sedan's measured (142,32,32) texel rather than the approximation of it that was there before.

    Returns the two lens centres, so the spec's TailPos comes off the real geometry.
    """
    src=(CONTENT/'sedan_taillights.txt').read_text().splitlines()
    V=[[float(x) for x in l.split()[1:4]] for l in src if l.startswith('v ')]
    dz=rear_z-min(v[2] for v in V)
    dy=centre_y-(min(v[1] for v in V)+max(v[1] for v in V))/2
    u,vv=uv(4)
    out=['# Generated by tools/build_car_trailer.py; the sedan tail-light mesh translated onto the trailer.',
         f'# Source game/content/sedan_taillights.txt, offset (0, {dy:.9f}, {dz:.9f}); X and all normals unchanged.']
    moved=[]; vi=0; side=None
    body=[]
    for l in src:
        if l.startswith('v '):
            x,yy,zz=[float(q) for q in l.split()[1:4]]
            moved.append((x,yy+dy,zz+dz)); body.append(f'v {x:.9f} {yy+dy:.9f} {zz+dz:.9f}')
        elif l.startswith('vt '): body.append(f'vt {u:.9f} {vv:.9f}')   # uv() already carries this model's V convention -- flipping again lands on index 0, the steel grey
        elif l.startswith('vn ') or l.startswith('f '): body.append(l)
    # split the faces into two named lens groups so the verifier can still sample each side
    lines=[]; group=None
    for l in body:
        if l.startswith('f '):
            ids=[int(c.split("/")[0])-1 for c in l.split()[1:4]]
            sgn=-1 if sum(moved[i][0] for i in ids)/3 < 0 else 1
            if sgn!=group: lines.append('g tail_lens_'+str(sgn)); group=sgn
        lines.append(l)
    (CONTENT/'car_trailer_taillights.txt').write_text('\n'.join(out+lines)+'\n')
    left=[q for q in moved if q[0]<0]; right=[q for q in moved if q[0]>0]
    return [tuple(sum(q[a] for q in half)/len(half) for a in range(3)) for half in (left,right)]

def generate():
    specs,rear=measurements();d=design(specs,rear)
    t=d['t'];w=d['deck_w']/2;f=d['front'];b=d['back'];y=d['deck_y'];r=d['radius'];ky=d['king'][1];kz=d['king'][2];az=d['axle_z'];cy=d['wheel_center_y'];wt=d['wall_t'];wh=d['wall_h']
    m=Model()
    # ONE SLAB, NOT PLANKS. The reference is the truck's own bed (strawberry: "too much detail. look
    # at the truck bed etc"), and that floor is TWO triangles -- a single 1.616 m2 quad at Y=0.125, no
    # board lines anywhere. Modelling nine separate boards with gaps cost 72 tris to say something the
    # fleet says with a flat surface and a palette colour, so the deck is one box like the truck's.
    m.box('deck',(-w,y-2*t,f),(w,y-t/4,b),2)
    for sign in [-1,1]:
        x=sign*(w-2*t)
        m.box('chassis_'+str(sign),(x-t,y-4*t,f),(x+t,y-2*t,b),3)
        m.beam('drawbar_'+str(sign),(sign*t,ky,kz+4*t),(sign*(w-2*t),y-3*t,f+d['deck_l']/4),2*t,2*t,0)
    m.box('axle',(-d['track']/2,cy-t,az-t),(d['track']/2,cy+t,az+t),3)
    # Low solid sideboards with top rails. Tailgate has visible hinge blocks and latches.
    # WALL SECTION IS THE TRUCK'S BED, measured: .250 thick, standing 1.000 above the floor. Mine were
    # t = .050 and .450 -- five times too thin and under half the height, which is what made the box
    # read as a tray rather than as fleet bodywork. No capping rail and no stake posts; both were
    # sub-centimetre trim at a scale nothing else in the fleet models.
    for sign in [-1,1]:
        xo=sign*w; xi=sign*(w-wt)
        m.box('side_'+str(sign),(min(xo,xi),y-t/2,f),(max(xo,xi),y+wh,b),1)
    # Gates TUCK INTO the sideboards (x +/- wt/2 of their inner face) and sit wt/4 in from the deck
    # ends. Butting them flush put the gate's outer face exactly on the side's inner face with matching
    # corners, and save(weld_positions=True) then merged those into an edge carrying four faces. Same
    # trap the deck hit; overlapping solids are how this model avoids it everywhere else too.
    for label,z in [('headboard',f+wt/4),('tailgate',b-wt-wt/4)]:
        m.box(label,(-w+wt/2,y-t/2,z),(w-wt/2,y+wh,z+wt),1)
    # NO WHEEL ARCHES (strawberry: "remove the wheel arches"). The fenders and the derived
    # segment-count machinery that sized them are both gone; the wheels now tuck flush under the deck
    # edge instead, which is what the narrowed track in design() is for.
    m.box('coupler',(-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t),0)
    # Gone with the rest of the trim: mudflaps, the coupler's latch and handle, the stand's foot pad
    # and the amber reflectors. Every one was a box under ~8 cm; nothing else in the fleet models at
    # that scale, so they read as noise on the silhouette rather than as detail.
    # Retractable stand is a separate closed component inside an exact split zone.
    stand_z=(kz+f)/2; stand_x=3*t
    m.box('landing_stand',(stand_x-t,d['ground'],stand_z-t/2),(stand_x+t,ky-t,stand_z+t/2),0)
    m.save('car_trailer_body.txt')
    tail_pos=sedan_lamps(b,y+wh/2)
    im=Image.new('RGBA',(4,2));im.putdata(COLORS);im.save(CONTENT/'car_trailer_palette.png')
    for name in TOW_CARS:
        h=Model(); rr=rear[name];hy=rr['y'];hz=rr['rear']+d['hitch_projection']
        h.box('receiver',(-t,hy-2*t,rr['section_z']-t),(t,hy-t,hz+t),0)
        h.component('ball')
        rings=[[(t*math.cos(i*math.pi/4),yy,hz+t*math.sin(i*math.pi/4)) for i in range(8)] for yy in [hy-t,hy+t]]
        h.prism(*rings,6);h.save(name+'_hitch.txt')
    # Explicit primitive colliders keep the open load space open (no enclosing hull).
    boxes=[]
    def box(lo,hi):boxes.append((tuple(hi[i]-lo[i] for i in range(3)),tuple((hi[i]+lo[i])/2 for i in range(3))))
    box((-w,y,f),(-w+wt,y+wh,b));box((w-wt,y,f),(w,y+wh,b))                 # sideboards, truck-bed section
    box((-w+wt,y,f),(w-wt,y+wh,f+wt));box((-w+wt,y,b-wt),(w-wt,y+wh,b))     # headboard and tailgate
    box((-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t))
    # Oriented drawbar collider boxes follow the two diagonal beams exactly in plan.
    hulls=[]
    for sign in [-1,1]:
        a=(sign*t,ky,kz+4*t);bb=(sign*(w-2*t),y-3*t,f+d['deck_l']/4)
        # Extra hull encloses inclined beam in Y; no cargo volume is filled.
        dx,dz=bb[0]-a[0],bb[2]-a[2]
        hulls.append(((2*t,bb[1]-a[1]+2*t,math.hypot(dx,dz)),tuple((a[i]+bb[i])/2 for i in range(3)),math.degrees(math.atan2(dx,dz))))
    def v(p):return 'new Vector3('+', '.join(f'{x:.6f}f' for x in p)+')'
    spec=f'''        // Car-scale open trailer. Every value is derived in notes/CAR_TRAILER_REPORT.md.
        static readonly Spec _car_trailer = new()
        {{
            Mass = {d['mass']:.6f}f,
            Body = "car_trailer_body.txt", Wheel = "quad_wheel.txt", WheelTex = "jeep_wheel_albedo.png", Palette = "car_trailer_palette.png",
            WheelRadius = {r:.6f}f, Engine = 0f, SteerMax = 0f, SteerMin = 0f, SpeedMax = 0f, SpeedMin = 0f, Brake = 0f,
            BoxSize = {v((2*w,2*t,b-f))}, BoxCenter = {v((0,y-t,0))},
            ExtraBoxes = new (Vector3, Vector3)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}),\n' for sz,c in boxes)+f'''            }},
            HullBoxes = new (Vector3 size, Vector3 center, float yawDeg)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}, {yaw:.6f}f),\n' for sz,c,yaw in hulls)+f'''                ({v((2*w,2*t,b-f))}, {v((0,y-t,0))}, 0f),
            }},
            Kingpin = {v(d['king'])},
            HitchYawLimit = {math.degrees(math.atan2(d['draw'],w+t/2)):.6f}f, // front rail corner remains behind pivot at full yaw
            LandingGearSize = {v((4*t,ky-t-d['ground'],4*t))}, LandingGearCenter = {v((stand_x,(ky-t+d['ground'])/2,stand_z))},
            LandingLegZoneMin = {v((stand_x-2*t,d['ground'],stand_z-2*t))}, LandingLegZoneMax = {v((stand_x+2*t,ky-t,stand_z+2*t))},
            ForwardGears = new[] {{ 1f }}, ReverseGear = 1f, ShiftUpRpm = 5000f,
            Sound = null, Fuel = 1000f, Health = {specs['quad']['Health']:.6f}f, Name = "Car Trailer",
            SteerPivot = Vector3.Zero, SteerAxis = Vector3.Zero,
            Wheels = new (float, float, float, bool)[]
            {{ (-{d['track']/2:.6f}f, {d['wheel_y']:.6f}f, {az:.6f}f, false), ({d['track']/2:.6f}f, {d['wheel_y']:.6f}f, {az:.6f}f, false) }},
            TailPos = new[] {{ {v(tail_pos[0])}, {v(tail_pos[1])} }},
            Parts = new (string, Color)[] {{ ("car_trailer_taillights.txt", new Color({COLORS[4][0]/255:.6f}f, {COLORS[4][1]/255:.6f}f, {COLORS[4][2]/255:.6f}f)) }},   // the sedan's own tail-lamp texel
        }};
        public static Vehicle BuildCarTrailer(int variant = 0) => Build(_car_trailer, variant, "car_trailer");
'''
    print('Generated car trailer and eight measured hitch meshes')
    return spec

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('--spec-out',type=Path)
    args=parser.parse_args();spec=generate()
    if args.spec_out: args.spec_out.write_text(spec)
