#!/usr/bin/env python3
"""Author an original wagon from the dimension brief in notes/vehicle_style.md.

No source body, roof, panel or wheel-anchor array is read by this generator.
Only the retained palette and sedan lamp parts are shared inputs. Wheels and
seat/steering parts are shared by reference in Vehicle.cs.
"""
import math
from pathlib import Path
import shutil
import struct
from measure_vehicles import CONTENT, ROOT, obj, fmt

PAINT = (0.125, 0.75)
DARK = (0.375, 0.25)

def sub(a, b):
    return tuple(x-y for x, y in zip(a, b))


def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


class Mesh:
    def __init__(self):
        self.v, self.vt, self.vn, self.f = [], [], [], []
        self.maps = [{}, {}, {}]

    def index(self, value, kind):
        value = tuple(round(x, 6) for x in value)
        values = (self.v, self.vt, self.vn)[kind]
        if value not in self.maps[kind]:
            values.append(value)
            self.maps[kind][value] = len(values)
        return self.maps[kind][value]

    def position(self, point, normal, uv):
        # Source-like seams: position records split only at a flat normal/UV boundary.
        key = (point, tuple(round(x, 4) for x in normal), uv)
        if key not in self.maps[0]:
            self.v.append(point)
            self.maps[0][key] = len(self.v)
        return self.maps[0][key]

    def tri(self, points, uvs=None):
        points = [tuple(round(x, 6) for x in p) for p in points]
        # Compute normals from the float32 positions ParseObj actually passes to Godot.
        loaded = [tuple(struct.unpack("f", struct.pack("f", x))[0] for x in p) for p in points]
        n = cross(sub(loaded[1], loaded[0]), sub(loaded[2], loaded[0]))
        length = math.sqrt(sum(x*x for x in n))
        assert length > 1e-10, ("degenerate authored triangle", points)
        normal = tuple(x/length for x in n)
        # OBJ V is up. This samples the sedan palette's alpha-zero (0,0) texel AFTER ParseObj's V flip.
        uvs = uvs or [(0.125, 0.75)] * 3
        self.f.append(tuple((self.position(p, normal, uv), self.index(uv, 1), self.index(normal, 2)) for p, uv in zip(points, uvs)))

    def quad(self, points, uv=None):
        for ids in ((0, 1, 2), (0, 2, 3)):
            self.tri([points[i] for i in ids], [uv]*3 if uv else None)

    def prism(self, x0, x1, yz, uv=None, joined=False):
        """Extrude a CCW polygon in the Y/Z plane; close all six faces."""
        left = [(x0, y, z) for y, z in yz]
        right = [(x1, y, z) for y, z in yz]
        self.quad(list(reversed(left)), uv)
        self.quad(right, uv)
        for i in range(4):
            if joined and i in (1, 3):
                continue  # end faces meet the roof underside and belt rail
            j = (i+1) % 4
            self.quad([left[i], left[j], right[j], right[i]], uv)

    def box(self, lo, hi, uv=None):
        x0, y0, z0 = lo
        x1, y1, z1 = hi
        self.prism(x0, x1, [(y0,z0), (y1,z0), (y1,z1), (y0,z1)], uv)

    def write(self, name):
        lines = ["# Generated by tools/build_wagon.py; metres, +Y up, forward -Z.",
                 "# Triangles only; explicit v/vt/vn; vt V is flipped by ContentProvider.ParseObj.", f"g {Path(name).stem}"]
        for tag, data in (("v", self.v), ("vt", self.vt), ("vn", self.vn)):
            lines.extend(tag + " " + " ".join(fmt(x) for x in value) for value in data)
        lines.extend("f " + " ".join("/".join(map(str, corner)) for corner in face) for face in self.f)
        (CONTENT / name).write_text("\n".join(lines) + "\n")



def outward_quad(mesh, points, direction, uv=None):
    n = cross(sub(points[1], points[0]), sub(points[2], points[0]))
    if sum(a*b for a,b in zip(n,direction)) < 0:
        points = list(reversed(points))
    mesh.quad(points, uv)


def build():
    assert (ROOT/'notes/vehicle_style.md').exists(), "Derive the house style first"
    body = Mesh()
    # Entirely new faceted side walls. Each arch has four flat edges, with a
    # 0.25 m deep return into the wheel opening. Front/rear axle Z: -1.56/+1.46.
    contour = [(-2.76,-.12)]
    for axle in (-1.56,1.46):
        contour += [(axle+z,y) for z,y in [(-.70,-.12),(-.50,.50),(0,.72),(.50,.50),(.70,-.12)]]
    contour += [(2.76,-.12)]

    def width(z):
        return 1.26 - max(0., abs(z)-2.32)*(.10/.44)

    for sign in (-1,1):
        for (z0,y0),(z1,y1) in zip(contour,contour[1:]):
            x0,x1 = sign*width(z0),sign*width(z1)
            i0,i1 = x0-sign*.25,x1-sign*.25
            # Outer skin, inner skin, wheel-arch/sill return and bevelled belt.
            outward_quad(body,[(x0,y0,z0),(x1,y1,z1),(x1,1.,z1),(x0,1.,z0)],(sign,0,0))
            outward_quad(body,[(i0,y0,z0),(i0,1.10,z0),(i1,1.10,z1),(i1,y1,z1)],(-sign,0,0),DARK)
            outward_quad(body,[(x0,y0,z0),(i0,y0,z0),(i1,y1,z1),(x1,y1,z1)],(0,-1,0),DARK)
            outward_quad(body,[(x0,1.,z0),(x1,1.,z1),(i1,1.10,z1),(i0,1.10,z0)],(0,1,0))
        for z,y in (contour[0],contour[-1]):
            x=sign*width(z);i=x-sign*.25
            outward_quad(body,[(x,y,z),(x,1.,z),(i,1.10,z),(i,y,z)],(0,0,z))

    # Underfloor stays inboard of the tyres; raised load deck starts behind the
    # shared rear seatbacks (maximum Z measured locally, not a copied body deck).
    body.box((-.99,-.27,-2.58),(.99,-.12,2.62),DARK)
    body.box((-.99,-.12,1.36),(.99,.18,2.65),DARK)
    # A new wedge bonnet: one top plane and a vertical front fascia.
    body.prism(-1.01,1.01,[(-.12,-2.76),(.91,-2.76),(1.10,-1.25),(-.12,-1.25)])
    # Rear lower tailgate has its own flat cargo sill; bumper tips define ±2.90.
    body.box((-1.01,.18,2.53),(1.01,1.10,2.68))
    for z0,z1 in ((-2.90,-2.76),(2.76,2.90)):
        body.box((-1.16,-.12,z0),(1.16,.16,z1),DARK)
    # Front grille (under the lamps), rear latch: fixed dark palette texel.
    body.box((-.48,.36,-2.79),(.48,.54,-2.76),DARK)
    body.box((-.23,.89,2.68),(.23,.96,2.70),DARK)

    # Flat thick roof, A/B/C/D sections. None is computed from sedan vertices.
    # 0.20 m rear posts frame a separate cargo window (0.93 base / 0.81 top).
    body.box((-1.23,1.92,-.80),(1.23,2.17,2.56))
    for sign in (-1,1):
        x0,x1=sorted((sign*.98,sign*1.23))
        body.prism(x0,x1,[(1.10,-1.25),(1.92,-.80),(1.92,-.55),(1.10,-1.00)], joined=True)
        for z0,z1 in ((.12,.37),(1.35,1.55)):
            body.prism(x0,x1,[(1.10,z0),(1.92,z0),(1.92,z1),(1.10,z1)], joined=True)
        body.prism(x0,x1,[(1.10,2.48),(1.92,2.36),(1.92,2.56),(1.10,2.68)], joined=True)
        # Continuous 0.12 m belt rail connects the inset side skins to the posts.
        body.box((x0,.98,-1.25),(x1,1.10,2.68))
    # Front/rear roof headers are provided by the slab; opaque apron is below
    # glass, leaving all eight apertures unbacked by body faces.
    body.write('wagon_body.txt')
    shutil.copyfile(CONTENT/'sedan_palette.png',CONTENT/'wagon_palette.png')

    panes = {
        'windshield': [(-.98,1.10,-1.25),(.98,1.10,-1.25),(.98,1.92,-.80),(-.98,1.92,-.80)],
        'rear': [(-.98,1.10,2.68),(-.98,1.92,2.56),(.98,1.92,2.56),(.98,1.10,2.68)],
    }
    for side,sign in [('l',-1),('r',1)]:
        x=sign*1.226
        panes[side+'_front']=[(x,1.10,-1.00),(x,1.10,.12),(x,1.92,.12),(x,1.92,-.55)]
        panes[side+'_rear']=[(x,1.10,.37),(x,1.10,1.35),(x,1.92,1.35),(x,1.92,.37)]
        panes[side+'_mid1']=[(x,1.10,1.55),(x,1.10,2.48),(x,1.92,2.36),(x,1.92,1.55)]
    for label,points in panes.items():
        mesh=Mesh()
        direction = (0,0,-1) if label=='windshield' else (0,0,1) if label=='rear' else (-1,0,0) if label.startswith('l_') else (1,0,0)
        outward_quad(mesh,points,direction)
        mesh.write('wagon_glass_'+label+'.txt')

    # Keep the lamp approach: existing lenses and colour, each translated to
    # the new fascia, paired with the same delta in SpotPos/TailPos in the spec.
    for lamp,delta in [('headlights',.150),('taillights',.012)]:
        source=obj(CONTENT/('sedan_'+lamp+'.txt'))
        lamps=Mesh()
        for face in source['faces']:
            cs=[tuple(int(i)-1 for i in c.split('/')) for c in face]
            lamps.tri([(source['vertices'][v][0],source['vertices'][v][1],source['vertices'][v][2]+delta) for v,t,n in cs],
                      [(source['uvs'][t][0],1-source['uvs'][t][1]) for v,t,n in cs])
        lamps.write('wagon_'+lamp+'.txt')
    saved=obj(CONTENT/'wagon_body.txt')
    assert saved['lo']==(-1.26,-.27,-2.9) and saved['hi']==(1.26,2.17,2.9), saved
    print('Body:',len(body.v),'v /',len(body.f),'triangles;',len(set(body.v)),'unique positions')
    print('AABB:',saved['lo'],saved['hi'])


if __name__=='__main__':
    build()
