#!/usr/bin/env python3
"""Rebuild closed component meshes and the measured spec; +Y up, front -Z."""
import math
from pathlib import Path
from PIL import Image
from measure_vehicles import ROOT, CONTENT, obj
from measure_car_trailer import measurements, design, TOW_CARS
from build_wagon import Mesh

COLORS = [(151,159,158,255),(88,111,87,255),(135,105,69,255),(46,49,48,255),
          (154,34,29,255),(225,157,49,255),(201,204,198,255),(22,25,25,255)]

def uv(color): return ((color%4+.5)/4,1-(color//4+.5)/2)

class Model(Mesh):
    def __init__(self):
        super().__init__(); self.groups=[]
    def component(self,name): self.groups.append((len(self.f),name))
    def polygon(self,ps,color):
        for i in range(1,len(ps)-1): self.tri([ps[0],ps[i],ps[i+1]],[uv(color)]*3)
    def prism(self,low,high,color):
        # Two corresponding rings. Wind each face away from the component centre.
        c=tuple(sum(p[i] for p in low+high)/len(low+high) for i in range(3))
        for ps in [low,list(reversed(high))]+[[low[i],high[i],high[(i+1)%len(low)],low[(i+1)%len(low)]] for i in range(len(low))]:
            a,b,d=ps[:3]; u=[b[i]-a[i] for i in range(3)];v=[d[i]-a[i] for i in range(3)]
            n=(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])
            if sum(n[i]*(a[i]-c[i]) for i in range(3))<0: ps=list(reversed(ps))
            self.polygon(ps,color)
    def box(self,name,lo,hi,color=0):
        self.component(name)
        self.prism([(lo[0],lo[1],lo[2]),(hi[0],lo[1],lo[2]),(hi[0],lo[1],hi[2]),(lo[0],lo[1],hi[2])],
                   [(lo[0],hi[1],lo[2]),(hi[0],hi[1],lo[2]),(hi[0],hi[1],hi[2]),(lo[0],hi[1],hi[2])],color)
    def beam(self,name,a,b,width,height,color=0):
        self.component(name)
        dx,dz=b[0]-a[0],b[2]-a[2];l=math.hypot(dx,dz); nx,nz=dz/l*width/2,-dx/l*width/2
        rings=[[(p[0]-nx,p[1]-height/2,p[2]-nz),(p[0]+nx,p[1]-height/2,p[2]+nz),
                (p[0]+nx,p[1]+height/2,p[2]+nz),(p[0]-nx,p[1]+height/2,p[2]-nz)] for p in [a,b]]
        self.prism(*rings,color)
    def save(self,name):
        self.write(name,weld_positions=True)
        p=CONTENT/name;lines=p.read_text().splitlines();out=[];face=0;groups=dict(self.groups)
        for line in lines:
            if line.startswith('# Generated'): line='# Generated by tools/build_car_trailer.py; metres, +Y up, front -Z.'
            if line.startswith('g '): continue
            if line.startswith('f '):
                if face in groups:out.append('g '+groups[face])
                face+=1
            out.append(line)
        p.write_text('\n'.join(out)+'\n')

def generate():
    specs,rear=measurements();d=design(specs,rear)
    t=d['t'];w=d['deck_w']/2;f=d['front'];b=d['back'];y=d['deck_y'];r=d['radius'];ky=d['king'][1];kz=d['king'][2];az=d['axle_z'];cy=d['wheel_center_y']
    m=Model()
    m.box('deck',(-w,y-2*t,f),(w,y-t/2,b),0)
    # Board count = floor(length / quad tyre width), gaps are t/5.
    count=math.floor(d['deck_l']/d['tyre_width']); step=(2*w-2*t)/count
    for i in range(count):
        m.box('board_'+str(i),(-w+t+i*step+t/10,y-t/2,f+t),(-w+t+(i+1)*step-t/10,y,b-t),2)
    for sign in [-1,1]:
        x=sign*(w-2*t)
        m.box('chassis_'+str(sign),(x-t,y-4*t,f),(x+t,y-2*t,b),3)
        m.beam('drawbar_'+str(sign),(sign*t,ky,kz+4*t),(sign*(w-2*t),y-3*t,f+d['deck_l']/4),2*t,2*t,0)
    m.box('axle',(-d['track']/2,cy-t,az-t),(d['track']/2,cy+t,az+t),3)
    # Low solid sideboards with top rails. Tailgate has visible hinge blocks and latches.
    for sign in [-1,1]:
        x=sign*(w-t/2)
        m.box('side_'+str(sign),(x-t/2,y,f),(x+t/2,y+r-t,b),1)
        m.box('side_rail_'+str(sign),(x-t,y+r-t,f),(x+t,y+r,b),0)
        for z in [f+t/2,az,b-t/2]:
            m.box('stake_'+str(sign)+'_'+str(z),(x-.75*t,y,z-t/2),(x+.75*t,y+r-t/2,z+t/2),0)
    for label,z in [('headboard',f+t/5),('tailgate',b-t-t/5)]:
        m.box(label,(-w+t,y,z),(w-t,y+r-t+t/5,z+t),1)
        m.box(label+'_rail',(-w+t,y+r-t,z),(w-t,y+r,z+t),0)
    for sign in [-1,1]:
        x=sign*w*.65
        m.box('hinge_'+str(sign),(x-2*t,y-t/2,b),(x+2*t,y+t/2,b+t),0)
        m.box('latch_'+str(sign),(sign*(w-2*t)-t/2,y+r-3*t,b),(sign*(w-2*t)+t/2,y+r-t,b+t/2),3)
    # Six flat crown segments. Extrude each annular segment as a closed prism.
    inner=r+.25+t; outer=inner+t
    for sign in [-1,1]:
        x=sign*d['track']/2; half=d['tyre_width']/2+t
        # Continuous annulus with explicit triangulated caps (concave outline must not fan across wheel).
        m.component('mudguard_'+str(sign))
        inn=[(cy+inner*math.sin(i*math.pi/6),az+inner*math.cos(i*math.pi/6)) for i in range(7)]
        out=[(cy+outer*math.sin(i*math.pi/6),az+outer*math.cos(i*math.pi/6)) for i in range(7)]
        def quad(ps): m.quad(ps,uv(0))
        for i in range(6):
            for xx,reverse in [(x-half,True),(x+half,False)]:
                ps=[(xx,*inn[i]),(xx,*inn[i+1]),(xx,*out[i+1]),(xx,*out[i])]
                # normal sign audited below; X+ should face +X
                a,bb,c=ps[:3];crossx=(bb[1]-a[1])*(c[2]-a[2])-(bb[2]-a[2])*(c[1]-a[1])
                if (crossx>0)==reverse:ps.reverse()
                quad(ps)
            for ring,reverse in [(out,False),(inn,True)]:
                ps=[(x-half,*ring[i]),(x+half,*ring[i]),(x+half,*ring[i+1]),(x-half,*ring[i+1])]
                if reverse: ps.reverse()
                quad(ps)
        for j,rev in [(0,False),(6,True)]:
            ps=[(x-half,*inn[j]),(x+half,*inn[j]),(x+half,*out[j]),(x-half,*out[j])]
            if rev:ps.reverse()
            quad(ps)
        m.box('mudflap_'+str(sign),(x-half,cy-r/2,az+outer),(x+half,cy+2*t,az+outer+t/2),3)
    m.box('coupler',(-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t),0)
    m.box('coupler_latch',(-t/2,ky+t,kz-t),(t/2,ky+2*t,kz+2*t),3)
    m.box('coupler_handle',(-t,ky+2*t,kz),(t,ky+2.5*t,kz+3*t),6)
    # Retractable stand is a separate closed component inside an exact split zone.
    stand_z=(kz+f)/2; stand_x=3*t
    m.box('landing_stand',(stand_x-t,d['ground']+t,stand_z-t/2),(stand_x+t,ky-t,stand_z+t/2),0)
    m.box('landing_foot',(stand_x-2*t,d['ground'],stand_z-2*t),(stand_x+2*t,d['ground']+t,stand_z+2*t),3)
    for sign in [-1,1]:
        x=sign*(w-3*t)
        m.box('amber_reflector_'+str(sign),(x-t,y+r-3*t,f-t/2),(x+t,y+r-t,f),5)
    m.save('car_trailer_body.txt')
    lamps=Model()
    for sign in [-1,1]:
        x=sign*(w-3*t)
        lamps.box('tail_lens_'+str(sign),(x-2*t,y-2*t,b),(x+2*t,y,b+t),4)
    lamps.save('car_trailer_taillights.txt')
    im=Image.new('RGBA',(4,2));im.putdata(COLORS);im.save(CONTENT/'car_trailer_palette.png')
    for name in TOW_CARS:
        h=Model(); rr=rear[name];hy=rr['y'];hz=rr['rear']+d['hitch_projection']
        h.box('receiver',(-t,hy-2*t,rr['section_z']-t),(t,hy-t,hz+t),0)
        h.component('ball')
        rings=[[(t*math.cos(i*math.pi/4),yy,hz+t*math.sin(i*math.pi/4)) for i in range(8)] for yy in [hy-t,hy+t]]
        h.prism(*rings,6);h.save(name+'_hitch.txt')
    # Explicit primitive colliders keep the open load space open (no enclosing hull).
    boxes=[]
    def box(lo,hi):boxes.append((tuple(hi[i]-lo[i] for i in range(3)),tuple((hi[i]+lo[i])/2 for i in range(3))))
    box((-w,y,f),( -w+t,y+r,b));box((w-t,y,f),(w,y+r,b))
    box((-w+t,y,f),(w-t,y+r,f+t));box((-w+t,y,b-t),(w-t,y+r,b))
    box((-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t))
    # Oriented drawbar collider boxes follow the two diagonal beams exactly in plan.
    hulls=[]
    for sign in [-1,1]:
        a=(sign*t,ky,kz+4*t);bb=(sign*(w-2*t),y-3*t,f+d['deck_l']/4)
        # Extra hull encloses inclined beam in Y; no cargo volume is filled.
        dx,dz=bb[0]-a[0],bb[2]-a[2]
        hulls.append(((2*t,bb[1]-a[1]+2*t,math.hypot(dx,dz)),tuple((a[i]+bb[i])/2 for i in range(3)),math.degrees(math.atan2(dx,dz))))
    def v(p):return 'new Vector3('+', '.join(f'{x:.6f}f' for x in p)+')'
    spec=f'''        // Car-scale open trailer. Every value is derived in notes/CAR_TRAILER_REPORT.md.
        static readonly Spec _car_trailer = new()
        {{
            Mass = {d['mass']:.6f}f,
            Body = "car_trailer_body.txt", Wheel = "quad_wheel.txt", WheelTex = "jeep_wheel_albedo.png", Palette = "car_trailer_palette.png",
            WheelRadius = {r:.6f}f, Engine = 0f, SteerMax = 0f, SteerMin = 0f, SpeedMax = 0f, SpeedMin = 0f, Brake = 0f,
            BoxSize = {v((2*w,2*t,b-f))}, BoxCenter = {v((0,y-t,0))},
            ExtraBoxes = new (Vector3, Vector3)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}),\n' for sz,c in boxes)+f'''            }},
            HullBoxes = new (Vector3 size, Vector3 center, float yawDeg)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}, {yaw:.6f}f),\n' for sz,c,yaw in hulls)+f'''                ({v((2*w,2*t,b-f))}, {v((0,y-t,0))}, 0f),
            }},
            Kingpin = {v(d['king'])},
            HitchYawLimit = {math.degrees(math.atan2(d['draw'],w+t/2)):.6f}f, // front rail corner remains behind pivot at full yaw
            LandingGearSize = {v((4*t,ky-t-d['ground'],4*t))}, LandingGearCenter = {v((stand_x,(ky-t+d['ground'])/2,stand_z))},
            LandingLegZoneMin = {v((stand_x-2*t,d['ground'],stand_z-2*t))}, LandingLegZoneMax = {v((stand_x+2*t,ky-t,stand_z+2*t))},
            ForwardGears = new[] {{ 1f }}, ReverseGear = 1f, ShiftUpRpm = 5000f,
            Sound = null, Fuel = 1000f, Health = {specs['quad']['Health']:.6f}f, Name = "Car Trailer",
            SteerPivot = Vector3.Zero, SteerAxis = Vector3.Zero,
            Wheels = new (float, float, float, bool)[]
            {{ (-{d['track']/2:.6f}f, {d['wheel_y']:.6f}f, {az:.6f}f, false), ({d['track']/2:.6f}f, {d['wheel_y']:.6f}f, {az:.6f}f, false) }},
            TailPos = new[] {{ {v((-w+3*t,y-t,b+t))}, {v((w-3*t,y-t,b+t))} }},
            Parts = new (string, Color)[] {{ ("car_trailer_taillights.txt", new Color(0.56f, 0.13f, 0.13f)) }},
        }};
        public static Vehicle BuildCarTrailer(int variant = 0) => Build(_car_trailer, variant, "car_trailer");
'''
    print('Generated car trailer and eight measured hitch meshes')
    return spec

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('--spec-out',type=Path)
    args=parser.parse_args();spec=generate()
    if args.spec_out: args.spec_out.write_text(spec)
