#!/usr/bin/env python3
"""Build the estate from measured sedan geometry. Run after measure_vehicles.py.

Keeps the sedan lower body, wheel arches, four seats and driving rig. Replaces
the greenhouse with a flat roof, A/B/C/D pillars, and eight separate panes.
All output faces are triangles with explicit per-corner UVs and normals.
"""
from __future__ import annotations

import math
from pathlib import Path
import shutil
import statistics
import struct

from measure_vehicles import CONTENT, ROOT, obj, read_specs, fmt, vec, table


def sub(a, b):
    return tuple(x-y for x, y in zip(a, b))


def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


class Mesh:
    def __init__(self):
        self.v, self.vt, self.vn, self.f = [], [], [], []
        self.maps = [{}, {}, {}]

    def index(self, value, kind):
        value = tuple(round(x, 6) for x in value)
        values = (self.v, self.vt, self.vn)[kind]
        if value not in self.maps[kind]:
            values.append(value)
            self.maps[kind][value] = len(values)
        return self.maps[kind][value]

    def tri(self, points, uvs=None):
        points = [tuple(round(x, 6) for x in p) for p in points]
        # Compute normals from the float32 positions ParseObj actually passes to Godot.
        loaded = [tuple(struct.unpack("f", struct.pack("f", x))[0] for x in p) for p in points]
        n = cross(sub(loaded[1], loaded[0]), sub(loaded[2], loaded[0]))
        length = math.sqrt(sum(x*x for x in n))
        if length < 1e-10:  # clipping at a source vertex can produce a line
            return
        normal = tuple(x/length for x in n)
        # OBJ V is up. This samples the sedan palette's alpha-zero (0,0) texel AFTER ParseObj's V flip.
        uvs = uvs or [(0.125, 0.75)] * 3
        self.f.append(tuple((self.index(p, 0), self.index(uv, 1), self.index(normal, 2)) for p, uv in zip(points, uvs)))

    def quad(self, points, uv=None):
        for ids in ((0, 1, 2), (0, 2, 3)):
            self.tri([points[i] for i in ids], [uv]*3 if uv else None)

    def prism(self, x0, x1, yz, uv=None):
        """Extrude a CCW polygon in the Y/Z plane; close all six faces."""
        left = [(x0, y, z) for y, z in yz]
        right = [(x1, y, z) for y, z in yz]
        self.quad(list(reversed(left)), uv)
        self.quad(right, uv)
        for i in range(4):
            j = (i+1) % 4
            self.quad([left[i], left[j], right[j], right[i]], uv)

    def box(self, lo, hi, uv=None):
        x0, y0, z0 = lo
        x1, y1, z1 = hi
        self.prism(x0, x1, [(y0,z0), (y1,z0), (y1,z1), (y0,z1)], uv)

    def write(self, name):
        lines = ["# Generated by tools/build_wagon.py; metres, +Y up, forward -Z.",
                 "# Triangles only; explicit v/vt/vn; vt V is flipped by ContentProvider.ParseObj.", f"g {Path(name).stem}"]
        for tag, data in (("v", self.v), ("vt", self.vt), ("vn", self.vn)):
            lines.extend(tag + " " + " ".join(fmt(x) for x in value) for value in data)
        lines.extend("f " + " ".join("/".join(map(str, corner)) for corner in face) for face in self.f)
        (CONTENT / name).write_text("\n".join(lines) + "\n")


def clip_below(poly, y):
    """Sutherland-Hodgman clipping, interpolating the source per-corner UV."""
    result = []
    for current, following in zip(poly, poly[1:] + poly[:1]):
        a, auv = current
        b, buv = following
        ina, inb = a[1] <= y, b[1] <= y
        if ina:
            result.append(current)
        if ina != inb:
            t = (y-a[1])/(b[1]-a[1])
            result.append((tuple(x+(z-x)*t for x,z in zip(a,b)), tuple(x+(z-x)*t for x,z in zip(auv,buv))))
    return result


def build():
    assert (ROOT / "notes/vehicle_measurements.md").exists(), "Measure the fleet first"
    specs = read_specs()
    sedan = specs["sedan"]
    source = sedan["mesh"]
    verts = source["vertices"]
    # These are vertex planes in the source mesh, selected by their existing rounded Y levels.
    level = lambda y: [v for v in verts if round(v[1], 3) == y]
    belt = statistics.median(v[1] for v in level(1.125))
    shoulder = statistics.median(v[1] for v in level(1.0))
    eaves = statistics.median(v[1] for v in level(1.875))
    roof_edge = statistics.median(v[1] for v in level(2.125))
    thickness = round(roof_edge - eaves, 6)
    extension = thickness
    roof_y = source["hi"][1]
    under_roof = roof_y - thickness
    outer_x = round(max(abs(v[0]) for v in level(1.875)), 6)
    inner_x = outer_x - thickness
    a_base = min(v[2] for v in level(1.125))
    a_top = min(v[2] for v in level(1.875))
    b_front = round(statistics.median(v[2] for v in level(1.91) if 0 < v[2] < 0.2), 6)
    b_back = b_front + thickness
    axle = max(w[2] for w in sedan["Wheels"])
    stretch_start = axle + sedan["WheelRadius"]
    tailgate = max(v[2] for v in level(0.875)) + extension
    old_rim_end = max(v[2] for v in level(1.125))
    c_front, c_back = stretch_start, stretch_start + thickness
    d_front, d_back = tailgate - thickness, tailgate
    assert b_back < c_front < c_back < d_front

    def stretch(v):
        x,y,z = v
        # Translate the rear fascia/bumper/exhaust by one roof thickness while retaining tyre arches.
        # Linear ramp starts BEHIND the rear tyre, becoming a rigid translation at the old tailgate plane.
        fraction = max(0., min(1., (z-stretch_start)/(tailgate-extension-stretch_start)))
        return (x,y,z+extension*fraction)

    body = Mesh()
    for face in source["faces"]:
        assert len(face) == 3
        indices = [tuple(int(i)-1 for i in c.split("/")) for c in face]
        poly = [(source["vertices"][v], (source["uvs"][t][0], 1-source["uvs"][t][1])) for v,t,n in indices]
        poly = clip_below(poly, belt)
        for i in range(1, len(poly)-1):
            points = [poly[j] for j in (0,i,i+1)]
            body.tri([stretch(p) for p,uv in points], [uv for p,uv in points])
    lower_triangles = len(body.f)

    # Flat roof, including its underside; no retained sedan roof or rear windscreen frame underneath it.
    body.box((-outer_x, under_roof, a_top), (outer_x, roof_y, tailgate))
    for sign in (-1,1):
        x0,x1 = sorted((sign*inner_x, sign*outer_x))
        body.prism(x0,x1, [(belt,a_base), (under_roof,a_top),
                          (under_roof,a_top+thickness), (belt,a_base+thickness)])
        for z0,z1 in ((b_front,b_back), (c_front,c_back), (d_front,d_back)):
            body.box((x0,belt,z0), (x1,under_roof,z1))
        # Rear belt rail fills the source boot's descending shoulder to the new vertical tailgate.
        body.box((x0,shoulder,old_rim_end), (x1,belt,tailgate))
    body.box((-inner_x,shoulder,d_front), (inner_x,belt,tailgate))
    # Fixed dark handle on the tailgate belt, below its glass; sizes derived from the same frame thickness.
    handle_y = (shoulder+belt)/2
    body.box((-thickness,handle_y-thickness/16,tailgate),
             (thickness,handle_y+thickness/16,tailgate+thickness/8), uv=(0.375,0.25))
    body.write("wagon_body.txt")
    shutil.copyfile(CONTENT / sedan["Palette"], CONTENT / "wagon_palette.png")

    # Eight independent four-corner panes, using existing GlassPaneLabels (mid1 = cargo side window).
    panes = {
        "windshield": [(-inner_x,belt,a_base), (inner_x,belt,a_base),
                       (inner_x,under_roof,a_top), (-inner_x,under_roof,a_top)],
        "rear": [(-inner_x,belt,tailgate), (-inner_x,under_roof,tailgate),
                 (inner_x,under_roof,tailgate), (inner_x,belt,tailgate)],
    }
    # Pane centre within the frame thickness avoids coplanar overlap with either frame skin.
    pane_x = (inner_x+outer_x)/2
    for side,sign in (("l",-1),("r",1)):
        x = sign*pane_x
        panes[f"{side}_front"] = [(x,belt,a_base+thickness), (x,belt,b_front),
                                  (x,under_roof,b_front), (x,under_roof,a_top+thickness)]
        for label,z0,z1 in (("rear",b_back,c_front),("mid1",c_back,d_front)):
            panes[f"{side}_{label}"] = [(x,belt,z0), (x,belt,z1), (x,under_roof,z1), (x,under_roof,z0)]
    for label,points in panes.items():
        mesh = Mesh()
        if label in ("windshield", "rear") or label.startswith("r_"):
            points = list(reversed(points))
        mesh.quad(points)
        mesh.write(f"wagon_glass_{label}.txt")

    # Lamps retain the sedan lens geometry and colours. Move the rear mesh by exactly the TailPos delta.
    mesh = obj(CONTENT / "sedan_taillights.txt")
    lamps = Mesh()
    for face in mesh["faces"]:
        corners = [tuple(int(i)-1 for i in c.split("/")) for c in face]
        lamps.tri([(mesh["vertices"][c[0]][0],mesh["vertices"][c[0]][1],mesh["vertices"][c[0]][2]+extension) for c in corners],
                  [(mesh["uvs"][c[1]][0],1-mesh["uvs"][c[1]][1]) for c in corners])
    lamps.write("wagon_taillights.txt")

    mesh = obj(CONTENT / "wagon_body.txt")
    expected = (source["size"][0], source["size"][1], source["size"][2]+extension)
    assert all(abs(x-y)<0.000002 for x,y in zip(mesh["size"],expected)), (mesh["size"],expected)
    roof_size = (2*outer_x, thickness, tailgate-a_top)
    roof_center = (0., (under_roof+roof_y)/2, (a_top+tailgate)/2)
    print("Wagon bounds:", vec(mesh["lo"]), vec(mesh["hi"]))
    print("RoofBox size/center:", vec(roof_size), vec(roof_center))
    print("Counts:", len(body.v), "vertices,", len(body.f), "triangles; retained lower triangles:", lower_triangles)

    out = ["## Wagon dimension derivation", "",
           "Design assumption: prioritize the requested sedan inheritance when the ambulance length limit conflicts with the measured files. The sedan is already longer than the ambulance. No sedan or ambulance measurement was altered. This assumption is not a user-approved waiver; the contradictory length limit remains unmet.", "",
           "Geometry is generated by `tools/build_wagon.py` from `sedan_body.txt` vertex planes and `_sedan.Wheels`. Lower body triangles are clipped at the measured beltline, the original upper body is removed, and the new roof and pillars are closed prisms. Rear extension ramps only behind the rear tyre; wheel arches and anchors remain at the sedan positions. The boot deck remains the cargo floor. New panes carry explicit normals and UVs.", ""]
    table(out, ["Dimension / construction", "Value (m)", "Computed source / rule"], [
        ["AABB min / max", vec(mesh["lo"]) + " / " + vec(mesh["hi"]), "Measured again from wagon_body.txt v records"],
        ["Length / width / height", vec((mesh["size"][2],mesh["size"][0],mesh["size"][1])), "Sedan length + extension; sedan width and height retained"],
        ["Rear extension / frame thickness", fmt(extension), f"Sedan roof-edge Y {fmt(roof_edge)} − eave Y {fmt(eaves)}"],
        ["Beltline / rear shoulder Y", f"{fmt(belt)} / {fmt(shoulder)}", "Sedan vertex planes at these Y values"],
        ["Roof top / underside Y", f"{fmt(roof_y)} / {fmt(under_roof)}", "Sedan maximum Y; subtract frame thickness"],
        ["Roof outer / inner half-width", f"{fmt(outer_x)} / {fmt(inner_x)}", "Maximum abs(X) on sedan eave plane; subtract frame thickness"],
        ["A-pillar front Z, bottom / top", f"{fmt(a_base)} / {fmt(a_top)}", "Minimum sedan Z at beltline / eave; pillar Z thickness = frame thickness"],
        ["B-pillar front / back Z", f"{fmt(b_front)} / {fmt(b_back)}", "Median front B-pillar vertex Z on sedan underside plane; add frame thickness"],
        ["C-pillar front / back Z", f"{fmt(c_front)} / {fmt(c_back)}", "Rear anchor Z + WheelRadius; add frame thickness"],
        ["D-pillar front / back Z", f"{fmt(d_front)} / {fmt(d_back)}", "Tailgate − frame thickness / tailgate"],
        ["Tailgate Z", fmt(tailgate), "Maximum sedan Z on Y=0.875 vertex plane + extension"],
        ["Rear belt rail start Z", fmt(old_rim_end), "Maximum sedan Z at beltline"],
        ["Glass side abs(X); Y span", f"{fmt(pane_x)}; {fmt(belt)} .. {fmt(under_roof)}", "Midpoint of inner/outer frame X; between beltline and roof underside"],
        ["Glass Z boundaries", "A→B; B→C; C→D; tailgate", "The corresponding pillar aperture edges above; windshield uses A-pillar front plane"],
        ["Handle width / height / depth", vec((thickness*2,thickness/8,thickness/8)), "Frame thickness × (2, 1/8, 1/8); centre Y = midpoint of shoulder and beltline"],
        ["RoofBox size / centre (XYZ)", vec(roof_size) + " / " + vec(roof_center), "Exact bounds of generated roof prism"],
        ["Wheelbase / front & rear track", f"{fmt(sedan['wheelbase'])} / {fmt(sedan['tracks'][0])}", "Unchanged sedan Wheels array"],
        ["Wheel radius / ride Y−r", f"{fmt(sedan['WheelRadius'])} / {fmt(sedan['Wheels'][0][1]-sedan['WheelRadius'])}", "Unchanged sedan radius and anchor Y"],
        ["Front / rear overhang", f"{fmt(min(sedan['axles'])-mesh['lo'][2])} / {fmt(mesh['hi'][2]-max(sedan['axles']))}", "Wagon AABB to front/rear axle; rear includes exhaust, as in sedan"],
    ])
    table(out, ["Comparison", "Sedan", "Wagon", "Fleet reference"], [
        ["Body length m", fmt(source["size"][2]), fmt(mesh["size"][2]), f"Ambulance {fmt(specs['ambulance']['mesh']['size'][2])}; Ural {fmt(specs['ural']['mesh']['size'][2])}"],
        ["Body width m", fmt(source["size"][0]), fmt(mesh["size"][0]), f"Ambulance {fmt(specs['ambulance']['mesh']['size'][0])}"],
        ["Body height m", fmt(source["size"][1]), fmt(mesh["size"][1]), f"Golf {fmt(specs['golf']['mesh']['size'][1])}; ambulance {fmt(specs['ambulance']['mesh']['size'][1])}"],
        ["Mass kg", fmt(sedan["Mass"]), fmt((sedan["Mass"]+specs["police"]["Mass"])/2), "Midpoint of sedan and police, which share length/width and seat positions"],
        ["Body v records / triangles", f"{len(source['vertices'])} / {len(source['faces'])}", f"{len(body.v)} / {len(body.f)}", f"Triangle ratio {len(body.f)/len(source['faces']):.6f}; vertex ratio {len(body.v)/len(source['vertices']):.6f}"],
    ])
    (ROOT / "notes/wagon_dimensions.md").write_text("\n".join(out))


if __name__ == "__main__":
    build()
