#!/usr/bin/env python3
"""Rebuild closed component meshes and the measured spec; +Y up, front -Z."""
import math
from pathlib import Path
from PIL import Image
from measure_vehicles import ROOT, CONTENT, obj
from measure_car_trailer import measurements, design, TOW_CARS, CLASSES
from build_wagon import Mesh

COLORS = [(151,159,158,255),(88,111,87,255),(135,105,69,255),(46,49,48,255),
          (142,32,32,255),(225,157,49,255),(201,204,198,255),(22,25,25,255)]

def uv(color): return ((color%4+.5)/4,1-(color//4+.5)/2)

class Model(Mesh):
    def __init__(self):
        super().__init__(); self.groups=[]
    def component(self,name): self.groups.append((len(self.f),name))
    def polygon(self,ps,color):
        for i in range(1,len(ps)-1): self.tri([ps[0],ps[i],ps[i+1]],[uv(color)]*3)
    def prism(self,low,high,color):
        # Two corresponding rings. Wind each face away from the component centre.
        c=tuple(sum(p[i] for p in low+high)/len(low+high) for i in range(3))
        for ps in [low,list(reversed(high))]+[[low[i],high[i],high[(i+1)%len(low)],low[(i+1)%len(low)]] for i in range(len(low))]:
            a,b,d=ps[:3]; u=[b[i]-a[i] for i in range(3)];v=[d[i]-a[i] for i in range(3)]
            n=(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])
            if sum(n[i]*(a[i]-c[i]) for i in range(3))<0: ps=list(reversed(ps))
            self.polygon(ps,color)
    def box(self,name,lo,hi,color=0):
        self.component(name)
        self.prism([(lo[0],lo[1],lo[2]),(hi[0],lo[1],lo[2]),(hi[0],lo[1],hi[2]),(lo[0],lo[1],hi[2])],
                   [(lo[0],hi[1],lo[2]),(hi[0],hi[1],lo[2]),(hi[0],hi[1],hi[2]),(lo[0],hi[1],hi[2])],color)
    def beam(self,name,a,b,width,height,color=0):
        self.component(name)
        dx,dz=b[0]-a[0],b[2]-a[2];l=math.hypot(dx,dz); nx,nz=dz/l*width/2,-dx/l*width/2
        rings=[[(p[0]-nx,p[1]-height/2,p[2]-nz),(p[0]+nx,p[1]-height/2,p[2]+nz),
                (p[0]+nx,p[1]+height/2,p[2]+nz),(p[0]-nx,p[1]+height/2,p[2]-nz)] for p in [a,b]]
        self.prism(*rings,color)
    def save(self,name):
        self.write(name,weld_positions=True)
        p=CONTENT/name;lines=p.read_text().splitlines();out=[];face=0;groups=dict(self.groups)
        for line in lines:
            if line.startswith('# Generated'): line='# Generated by tools/build_car_trailer.py; metres, +Y up, front -Z.'
            if line.startswith('g '): continue
            if line.startswith('f '):
                if face in groups:out.append('g '+groups[face])
                face+=1
            out.append(line)
        p.write_text('\n'.join(out)+'\n')


def sedan_lamp_proud():
    """How far the sedan's lens stands out of the tail it is set into. Measured, and small.

    The obvious readings are both wrong. Against the body's rear-most point (2.9424) the lens is 154 mm
    RECESSED -- but that point is the bumper, down at Y -0.27..1.00. And there is no body vertex inside
    the lens's own Y band at all, so sampling by height finds nothing. What the sedan actually has is a
    stack of tail planes -- 2.7265, 2.7562, 2.7644, 2.7993, 2.8662, 2.9424 -- with the lens's rear face
    at 2.7880 sitting BETWEEN two of them: 24 mm proud of the one behind it, 11 mm inside the one in
    front. So the honest relationship is "flush to within a couple of centimetres", not a block hung off
    the back, and the number is the offset from the nearest plane behind the lens."""
    body=obj(CONTENT/'sedan_body.txt'); lamp=obj(CONTENT/'sedan_taillights.txt')
    rear=lamp['hi'][2]
    return rear-max(v[2] for v in body['vertices'] if v[2] <= rear+1e-6 and v[2] > 1.5)


def sedan_lamps(rear_z, centre_y, half_width, inset, out_name):
    """The SEDAN's tail lights, moved -- not a pair of boxes shaped like them.

    strawberry: "the tail lights should be off the sedan". Parts are drawn with a flat SolidMat, so
    only the geometry travels; the mesh keeps its 56 verts / 20 tris and its exact 2.2269 x 0.3291 x
    0.1899 section, and is translated so its front face meets the trailer's rear and its lenses centre
    on the tailgate. X is untouched: at +/-1.1135 they already sit inside a 2.462 deck, which is why
    they fit a trailer at all. UVs are re-pointed at the trailer palette's own red -- itself now the
    sedan's measured (142,32,32) texel rather than the approximation of it that was there before.

    X is NOT untouched any more. On the sedan the lenses inset .1476 from the body side; on a 2.100
    deck they reached |X| 1.1135 against a 1.050 side and hung 63.5 mm out past the trailer, which is a
    defect and not a style. Each lens moves inboard as a RIGID pair -- mirrored, equal and opposite --
    so the lens keeps its own shape and only the spacing changes (strawberry: "bring the tail lights
    closer together"). The inset it lands on is the sedan's own.

    Returns the two lens centres, so the spec's TailPos comes off the real geometry.
    """
    src=(CONTENT/'sedan_taillights.txt').read_text().splitlines()
    V=[[float(x) for x in l.split()[1:4]] for l in src if l.startswith('v ')]
    # The lens's REAR face lands proud of the tailgate by exactly what it stands out of the sedan's
    # own tail panel. Seating its FRONT face on the rear plane instead -- what I did first -- buries
    # nothing and stands the whole 190 mm depth out in the air, six times the sedan's relationship.
    dz=(rear_z+sedan_lamp_proud())-max(v[2] for v in V)
    dy=centre_y-(min(v[1] for v in V)+max(v[1] for v in V))/2
    # PER SIDE, not one shift for both: the sedan's lens pair is not symmetric (max |X| is 1.113476
    # on the left and 1.113453 on the right, 23 um apart), so a single offset lands the two lenses at
    # different insets. Each side is solved to the same target instead.
    target=half_width-inset
    dxr=max(v[0] for v in V)-target; dxl=min(v[0] for v in V)+target
    u,vv=uv(4)
    out=['# Generated by tools/build_car_trailer.py; the sedan tail-light mesh translated onto the trailer.',
         f'# Source game/content/sedan_taillights.txt, offset (0, {dy:.9f}, {dz:.9f}); X and all normals unchanged.']
    moved=[]; vi=0; side=None
    body=[]
    for l in src:
        if l.startswith('v '):
            x,yy,zz=[float(q) for q in l.split()[1:4]]
            x-= dxr if x>0 else dxl
            moved.append((x,yy+dy,zz+dz)); body.append(f'v {x:.9f} {yy+dy:.9f} {zz+dz:.9f}')
        elif l.startswith('vt '): body.append(f'vt {u:.9f} {vv:.9f}')   # uv() already carries this model's V convention -- flipping again lands on index 0, the steel grey
        elif l.startswith('vn ') or l.startswith('f '): body.append(l)
    # split the faces into two named lens groups so the verifier can still sample each side
    lines=[]; group=None
    for l in body:
        if l.startswith('f '):
            ids=[int(c.split("/")[0])-1 for c in l.split()[1:4]]
            sgn=-1 if sum(moved[i][0] for i in ids)/3 < 0 else 1
            if sgn!=group: lines.append('g tail_lens_'+str(sgn)); group=sgn
        lines.append(l)
    (CONTENT/out_name).write_text('\n'.join(out+lines)+'\n')
    left=[q for q in moved if q[0]<0]; right=[q for q in moved if q[0]>0]
    return [tuple(sum(q[a] for q in half)/len(half) for a in range(3)) for half in (left,right)]

def generate(cls='small', specs=None, rear=None):
    """One size class. Every dimension still comes out of design(); the class only chooses a length
    fraction, how many half-wall-sections of extra track, and how many axles."""
    if specs is None: specs,rear=measurements()
    d=design(specs,rear,cls); key=d['key']
    t=d['t'];w=d['deck_w']/2;f=d['front'];b=d['back'];y=d['deck_y'];r=d['radius'];ky=d['king'][1];kz=d['king'][2];az=d['axle_z'];cy=d['wheel_center_y'];wt=d['wall_t'];wh=d['wall_h']
    m=Model()
    drawbars=[((sign*t,ky,kz+4*t),(sign*(w-2*t),y-wt/2,f+d['deck_l']/4)) for sign in (-1,1)]
    # ONE SLAB, NOT PLANKS. The reference is the truck's own bed (strawberry: "too much detail. look
    # at the truck bed etc"), and that floor is TWO triangles -- a single 1.616 m2 quad at Y=0.125, no
    # board lines anywhere. Modelling nine separate boards with gaps cost 72 tris to say something the
    # fleet says with a flat surface and a palette colour, so the deck is one box like the truck's.
    # ONE SECTION FOR THE WHOLE BOX (strawberry: "make edges consistent"). Deck, sideboards and both
    # gates are all wt = the truck bed's .250; nothing in the cargo box is a different thickness any
    # more. The separate chassis rails are gone with them -- they were t = .050 members under a .0875
    # deck, and a .250 slab IS the under-frame, which is how the truck carries its own bed (floor at
    # Y .125 over structure down to -.125, exactly .250).
    # The deck is INSET half a section inside the walls rather than flush with them: sharing the outer
    # plane put two coplanar faces on |X| = w with an overlapping Y band, which z-fights.
    m.box('deck',(-w+wt/2,y-wt,f+wt/2),(w-wt/2,y,b-wt/2),2)
    for sign,(a,bb) in zip((-1,1),drawbars):
        m.beam('drawbar_'+str(sign),a,bb,2*t,2*t,0)
    # NO AXLE BAR (strawberry: "its the axle. remove the axle"). With the wheels flush against the
    # sideboards there is nothing for it to span, and a thin rod reaching out to outboard wheels was
    # the thing that read as inconsistent under the deck.

    # Low solid sideboards with top rails. Tailgate has visible hinge blocks and latches.
    # WALL SECTION IS THE TRUCK'S BED, measured: .250 thick, standing 1.000 above the floor. Mine were
    # t = .050 and .450 -- five times too thin and under half the height, which is what made the box
    # read as a tray rather than as fleet bodywork. No capping rail and no stake posts; both were
    # sub-centimetre trim at a scale nothing else in the fleet models.
    rake=d['rake']
    for sign in [-1,1]:
        xo=sign*w; xi=sign*(w-wt)
        if rake:
            # RAKED FRONT: the side's leading edge leans back as it rises, so the profile in Y/Z is a
            # trapezoid, not a rectangle. This is the whole of the horsebox silhouette -- a box with a
            # wedge nose reads as a horsebox where a plain box reads as a van.
            prof=[(y-wt,f),(y-wt,b),(y+wh,b),(y+wh,f+rake)]
            m.component('side_'+str(sign))
            m.prism([(min(xo,xi),py,pz) for py,pz in prof],[(max(xo,xi),py,pz) for py,pz in prof],1)
        else:
            m.box('side_'+str(sign),(min(xo,xi),y-wt,f),(max(xo,xi),y+wh,b),1)
    # The GATES own the ends now: their outer faces are f and b, so nothing stands proud of them. The
    # deck used to overhang the tailgate by wt/4, which is the lip that read as a mis-modelled edge.
    # They still tuck into the sideboards (x +/- wt/2 past the inner face) -- butting flush puts the
    # gate's outer face exactly on the side's inner face with matching corners, and
    # save(weld_positions=True) merges those into an edge carrying four faces.
    if rake:
        # The headboard IS the wedge: same section, leaning back with the sides it sits between.
        prof=[(y-wt,f),(y-wt,f+wt),(y+wh,f+rake+wt),(y+wh,f+rake)]
        m.component('headboard')
        m.prism([(-w+wt/2,py,pz) for py,pz in prof],[(w-wt/2,py,pz) for py,pz in prof],1)
        m.box('tailgate',(-w+wt/2,y-wt,b-wt),(w-wt/2,y+wh,b),1)
    else:
        for label,z in [('headboard',f),('tailgate',b-wt)]:
            m.box(label,(-w+wt/2,y-wt,z),(w-wt/2,y+wh,z+wt),1)
    # NO WHEEL ARCHES (strawberry: "remove the wheel arches"). The widened track in design() keeps
    # the tyres outboard of the wider box with the same construction-module clearance.
    # A ROOF makes it a horsebox rather than a very tall open trailer. One slab of the same wall
    # section as everything else, overlapping the walls it sits on (never butting flush -- coincident
    # corners get welded and the shared edge then carries four faces).
    if d['roof_top'] is not None:
        m.box('roof',(-w,y+wh-wt/2,f+rake),(w,y+wh+wt/2,b),1)   # starts where the raked front reaches it
    m.box('coupler',(-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t),0)
    # Gone with the rest of the trim: mudflaps, the coupler's latch and handle, the stand's foot pad
    # and the amber reflectors. Every one was a box under ~8 cm; nothing else in the fleet models at
    # that scale, so they read as noise on the silhouette rather than as detail.
    # Retractable stand is a separate closed component inside an exact split zone.
    stand_z=(kz+f)/2; stand_x=3*t
    m.box('landing_stand',(stand_x-t,d['ground'],stand_z-t/2),(stand_x+t,ky-t,stand_z+t/2),0)
    m.save(key+'_body.txt')
    # Lamps sit at the same absolute height on every class -- half the TRUCK BED's wall height above
    # the floor. Centring them on this class's own wall put the horsebox's lamps at 1.07, up by its
    # roofline, because its walls are twice as tall.
    tail_pos=sedan_lamps(b,d['lamp_y'],w,d['lamp_inset'],key+'_taillights.txt')
    im=Image.new('RGBA',(4,2));im.putdata(COLORS);im.save(CONTENT/'car_trailer_palette.png')
    for name in (TOW_CARS if cls=='dinky' else []):   # hitches live on the CARS; emit them once
        h=Model(); rr=rear[name];hy=rr['y'];hz=rr['rear']+d['hitch_projection']
        h.box('receiver',(-t,hy-2*t,rr['section_z']-t),(t,hy-t,hz+t),0)
        h.component('ball')
        rings=[[(t*math.cos(i*math.pi/4),yy,hz+t*math.sin(i*math.pi/4)) for i in range(8)] for yy in [hy-t,hy+t]]
        h.prism(*rings,6);h.save(name+'_hitch.txt')
    # Explicit primitive colliders keep the open load space open (no enclosing hull).
    boxes=[]
    def box(lo,hi):boxes.append((tuple(hi[i]-lo[i] for i in range(3)),tuple((hi[i]+lo[i])/2 for i in range(3))))
    box((-w,y,f),(-w+wt,y+wh,b));box((w-wt,y,f),(w,y+wh,b))                 # sideboards, truck-bed section
    # The raked headboard's collider is its AABB -- front face at f, back face where the wedge's top
    # edge lands. Slightly proud of the leaning panel at the top corner, which is outside the vehicle.
    box((-w+wt,y,f),(w-wt,y+wh,f+rake+wt));box((-w+wt,y,b-wt),(w-wt,y+wh,b))
    if d['roof_top'] is not None: box((-w,y+wh-wt/2,f+rake),(w,y+wh+wt/2,b))   # the roof is solid too
    box((-2*t,ky-t,kz-2*t),(2*t,ky+t,kz+4*t))
    # Oriented drawbar collider boxes follow the two diagonal beams exactly in plan.
    hulls=[]
    for a,bb in drawbars:
        # Use the mesh endpoints and the absolute rise: the lowered bed makes these beams descend.
        # Signed rise used to emit a negative collider height, and y-3*t missed the slab midpoint.
        dx,dz=bb[0]-a[0],bb[2]-a[2]
        hulls.append(((2*t,abs(bb[1]-a[1])+2*t,math.hypot(dx,dz)),tuple((a[i]+bb[i])/2 for i in range(3)),math.degrees(math.atan2(dx,dz))))
    def v(p):return 'new Vector3('+', '.join(f'{x:.6f}f' for x in p)+')'
    # One row per wheel: every axle in axle_zs, both sides. A tandem class emits four.
    wheel_rows=', '.join(f'(-{d["track"]/2:.6f}f, {d["wheel_y"]:.6f}f, {z:.6f}f, false), ({d["track"]/2:.6f}f, {d["wheel_y"]:.6f}f, {z:.6f}f, false)'
                         for z in d['axle_zs'])
    Cls=cls.capitalize()
    spec=f'''        // {d['display']}: car-scale open trailer, {d['axles']} axle(s). Derived in notes/CAR_TRAILER_REPORT.md.
        static readonly Spec _{key} = new()
        {{
            Mass = {d['mass']:.6f}f,
            Body = "{key}_body.txt", Wheel = {d['wheel_mesh']}, WheelTex = {d['wheel_tex']}, Palette = "car_trailer_palette.png",
            WheelRadius = {r:.6f}f, Engine = 0f, SteerMax = 0f, SteerMin = 0f, SpeedMax = 0f, SpeedMin = 0f, Brake = 0f,
            BoxSize = {v((2*w,wt,b-f))}, BoxCenter = {v((0,y-wt/2,0))},   // the deck slab itself; the load space above it stays open
            ExtraBoxes = new (Vector3, Vector3)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}),\n' for sz,c in boxes)+f'''            }},
            HullBoxes = new (Vector3 size, Vector3 center, float yawDeg)[]
            {{
'''+''.join(f'                ({v(sz)}, {v(c)}, {yaw:.6f}f),\n' for sz,c,yaw in hulls)+f'''                ({v((2*w,wt,b-f))}, {v((0,y-wt/2,0))}, 0f),
            }},
            Kingpin = {v(d['king'])},
            HitchYawLimit = {math.degrees(math.atan2(d['draw'],w+t/2)):.6f}f, // front rail corner remains behind pivot at full yaw
            LandingGearSize = {v((4*t,ky-t-d['ground'],4*t))}, LandingGearCenter = {v((stand_x,(ky-t+d['ground'])/2,stand_z))},
            LandingLegZoneMin = {v((stand_x-2*t,d['ground'],stand_z-2*t))}, LandingLegZoneMax = {v((stand_x+2*t,ky-t,stand_z+2*t))},
            ForwardGears = new[] {{ 1f }}, ReverseGear = 1f, ShiftUpRpm = 5000f,
            Sound = null, Fuel = 1000f, Health = {specs['quad']['Health']:.6f}f, Name = "{d['display']}",
            SteerPivot = Vector3.Zero, SteerAxis = Vector3.Zero,
            Wheels = new (float, float, float, bool)[]
            {{ {wheel_rows} }},
            TailPos = new[] {{ {v(tail_pos[0])}, {v(tail_pos[1])} }},
            Parts = new (string, Color)[] {{ ("{key}_taillights.txt", new Color({COLORS[4][0]/255:.6f}f, {COLORS[4][1]/255:.6f}f, {COLORS[4][2]/255:.6f}f)) }},   // the sedan's own tail-lamp texel
        }};
        public static Vehicle Build{Cls}Trailer(int variant = 0) => Build(_{key}, variant, "{key}");
'''
    print(f'Generated {cls} trailer ({d["deck_l"]:.3f} x {d["deck_w"]:.3f}, {d["axles"]} axle(s))')
    return spec

def generate_all():
    """All three size classes off one measurement pass; returns the concatenated spec text."""
    specs,rear=measurements()
    return '\n'.join(generate(c,specs,rear) for c in CLASSES)


if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser()
    parser.add_argument('--spec-out',type=Path); parser.add_argument('--class',dest='cls',default=None)
    args=parser.parse_args()
    spec=generate(args.cls,*measurements()) if args.cls else generate_all()
    if args.spec_out: args.spec_out.write_text(spec)
