"""Generate the Thermometer item (9346): mesh, palette albedo, inventory icon, manifest row.

strawberry 2026-10-07: "add a thermometer item that adds the temperature in °c/f on the temp bar".

A placeholder in the palette style of the hand-authored items (9320 pencil, 9321 eraser): a glass tube with a red
bulb and a red column in its lower half, a grey cap. Long axis Z, metres, the same orientation as the pencil.

Format notes, matched to game/content/items/9320.txt rather than assumed:
  - a triangle soup: per-triangle v/vt/vn triples, `f i/i/i j/j/j k/k/k`;
  - flat normals; every UV is a palette CELL CENTRE on a 4x2 texture (both rows identical, so a V flip in the
    loader cannot pick the wrong colour);
  - CLOCKWISE around the outward normal -- the shipped meshes run CW (cow tools measured 0/44, 0/64, 0/52 CCW),
    which is Godot's front face. Built CCW below and reversed on write.

Run: python3 tools/gen_thermometer.py   (writes into game/content/items/)
"""
import json, math, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "game", "content", "items")
ID = 9346

# palette cells: 0 glass, 1 red, 2 grey cap, 3 dark (scale ticks)
PALETTE = [(228, 236, 240), (196, 32, 30), (128, 130, 136), (44, 44, 48)]


def uv(cell):
    return ((cell + 0.5) / 4.0, 0.75)


tris = []   # (p0, p1, p2, cell), CCW about the outward normal


def quad(a, b, c, d, cell):
    tris.append((a, b, c, cell))
    tris.append((a, c, d, cell))


def ring(r, z, n, phase=0.0):
    return [(r * math.cos(phase + 2 * math.pi * i / n), r * math.sin(phase + 2 * math.pi * i / n), z) for i in range(n)]


def prism(r, z0, z1, n, cell, cap0=False, cap1=False):
    lo, hi = ring(r, z0, n), ring(r, z1, n)
    for i in range(n):
        j = (i + 1) % n
        quad(lo[i], lo[j], hi[j], hi[i], cell)          # side, outward
    if cap0:
        for i in range(n):
            tris.append(((0, 0, z0), lo[(i + 1) % n], lo[i], cell))   # facing -Z
    if cap1:
        for i in range(n):
            tris.append(((0, 0, z1), hi[i], hi[(i + 1) % n], cell))   # facing +Z


def sphere(c, r, n_lat, n_lon, cell):
    cx, cy, cz = c
    def p(la, lo):
        th = math.pi * la / n_lat           # 0 = +Z pole
        ph = 2 * math.pi * lo / n_lon
        return (cx + r * math.sin(th) * math.cos(ph), cy + r * math.sin(th) * math.sin(ph), cz + r * math.cos(th))
    for la in range(n_lat):
        for lo in range(n_lon):
            a, b = p(la, lo), p(la, lo + 1)
            c2, d = p(la + 1, lo + 1), p(la + 1, lo)
            if la == 0:
                tris.append((a, d, c2, cell))
            elif la == n_lat - 1:
                tris.append((a, d, b, cell))
            else:
                quad(a, d, c2, b, cell)


N = 8
R = 0.0045
prism(R, -0.056, -0.004, N, 1)                  # the red column, lower half
prism(R, -0.004, 0.058, N, 0)                   # the glass, upper half
prism(R * 1.15, 0.058, 0.066, N, 2, cap1=True)  # the cap
sphere((0.0, 0.0, -0.062), 0.0075, 5, N, 1)     # the bulb
# three scale ticks proud of the glass on +X, so it reads as a THERMOMETER and not a vial
for k in range(4):
    z = 0.006 + k * 0.012
    x = R * 0.98 + 0.0008   # just proud of the glass, facing +X
    quad((x, -0.0016, z), (x, 0.0016, z), (x, 0.0016, z + 0.0014), (x, -0.0016, z + 0.0014), 3)


def sub(a, b): return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
def cross(a, b): return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])
def norm(v):
    l = math.sqrt(sum(x * x for x in v)) or 1.0
    return tuple(x / l for x in v)


lines = ["# generated by tools/gen_thermometer.py -> Godot item mesh (up=y fwd=-z scale=1.0 det=+1 winding-reversed, RH Y-up)"]
vs, vts, vns, fs = [], [], [], []
xs, ys, zs = [], [], []
for (p0, p1, p2, cell) in tris:
    n = norm(cross(sub(p1, p0), sub(p2, p0)))   # CCW -> outward
    u, v = uv(cell)
    base = len(vs) + 1
    for p in (p0, p2, p1):                      # REVERSED: clockwise about the outward normal
        vs.append(p); vts.append((u, v)); vns.append(n)
        xs.append(p[0]); ys.append(p[1]); zs.append(p[2])
    fs.append((base, base + 1, base + 2))
lines += [f"v {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}" for p in vs]
lines += [f"vt {t[0]:.9f} {t[1]:.9f}" for t in vts]
lines += [f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}" for n in vns]
lines += [f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}" for a, b, c in fs]
open(os.path.join(ROOT, f"{ID}.txt"), "w").write("\n".join(lines) + "\n")

from PIL import Image, ImageDraw
pal = Image.new("RGB", (4, 2))
for i, col in enumerate(PALETTE):
    pal.putpixel((i, 0), col); pal.putpixel((i, 1), col)
pal.save(os.path.join(ROOT, f"{ID}.png"))

# the inventory icon: drawn, not baked -- a 1x1 item at 256 px, the tube on the diagonal so it fills the cell
S = 256
ic = Image.new("RGBA", (S, S), (0, 0, 0, 0))
d = ImageDraw.Draw(ic)
def along(t, off=0.0):
    # t 0..1 from bulb (lower-left) to cap (upper-right); off = perpendicular offset in px
    x0, y0, x1, y1 = 60, 200, 206, 54
    ux, uy = (x1 - x0), (y1 - y0)
    L = math.hypot(ux, uy); px, py = -uy / L, ux / L
    return (x0 + ux * t + px * off, y0 + uy * t + py * off)
W = 16
outline = (40, 44, 52, 255)
def tube(t0, t1, w, fill):
    pts = [along(t0, -w), along(t1, -w), along(t1, w), along(t0, w)]
    d.polygon(pts, fill=fill, outline=outline)
tube(0.05, 0.93, W + 3, outline)                       # dark rim
tube(0.05, 0.93, W, PALETTE[0] + (255,))               # glass
tube(0.05, 0.52, W - 7, PALETTE[1] + (255,))           # the red column
for k in range(6):                                     # scale
    t = 0.30 + k * 0.1
    a, b = along(t, W - 2), along(t, W - 9 if k % 2 else W - 13)
    d.line([a, b], fill=PALETTE[3] + (255,), width=3)
tube(0.92, 1.0, W + 4, PALETTE[2] + (255,))            # cap
bx, by = along(0.0)
d.ellipse([bx - 27, by - 27, bx + 27, by + 27], fill=PALETTE[1] + (255,), outline=outline, width=4)
d.ellipse([bx - 12, by - 16, bx - 2, by - 6], fill=(240, 120, 110, 255))   # a highlight
ic.save(os.path.join(ROOT, "icons", f"{ID}.png"))

# the manifest row: box + centre from the mesh itself, the shape every other row has
man_path = os.path.join(ROOT, "items_manifest.json")
man = json.load(open(man_path))
box = [round(max(xs) - min(xs), 4), round(max(ys) - min(ys), 4), round(max(zs) - min(zs), 4)]
ctr = [round((max(xs) + min(xs)) / 2, 4), round((max(ys) + min(ys)) / 2, 4), round((max(zs) + min(zs)) / 2, 4)]
man[str(ID)] = {"box": box, "center": ctr, "color": None, "name": "Thermometer", "obj": f"{ID}.txt",
                "parts": 1, "tex": f"{ID}.png", "type": "Generic"}
json.dump(man, open(man_path, "w"), indent=0, sort_keys=True)   # the file's own shape: no indent, sorted keys
print(f"{ID}: {len(fs)} tris, box {box}, centre {ctr}")
