#!/usr/bin/env python3
"""Fold a cardboard box's flaps shut -> content/objects/Cardboard_N_closed.obj.

master 2026-09-07 asked to "extract the closed cardboard box variants". ⚠ THERE ARE NONE TO EXTRACT. The game has
exactly four cardboard props (Objects/Small/Business/Cardboard_0..3), their meshes are IDENTICAL in pairs (0==2,
1==3, vertex for vertex), and the only difference between the pairs is a flat material colour -- cardboard_0.mat
(0.559,0.445,0.357) vs cardboard_1.mat (0.735,0.540,0.389), neither of which carries a texture at all. Two shapes,
two shades of tan, all four OPEN.

So the closed state is GENERATED, the same way the barbecue's lid had to be. Every box is 16 unique positions: a
body (x +-0.4333, y +-0.2779, z 0..0.4337 on Cardboard_0) plus four flaps splayed outward and upward past the rim.
Closing it is folding each flap about its own hinge edge until it lies flat on the top plane, pointing inward --
the length of the flap is preserved, so it is the same cardboard, folded.
"""
import sys, os, math

def close_box(src, dst):
    head, V, rest = [], [], []
    for line in open(src):
        if line.startswith("v "): V.append([float(x) for x in line.split()[1:4]])
        elif line.startswith(("#", "g ", "o ")): head.append(line.rstrip("\n"))
        else: rest.append(line)
    if not V: return None
    xs = sorted({round(v[0], 4) for v in V}); ys = sorted({round(v[1], 4) for v in V})
    # THE BODY is the inner box; its walls are the second plane in from each end on x and y.
    x0, x1 = xs[1], xs[-2]
    y0, y1 = ys[1], ys[-2]
    inside = lambda v: x0 - 1e-4 <= v[0] <= x1 + 1e-4 and y0 - 1e-4 <= v[1] <= y1 + 1e-4
    # ...and the RIM is the highest vertex that is actually ON the body, not a plane picked by index -- reading
    # zs[-3] worked on one box and grabbed a flap tip on another, which is how the first pass folded 12 verts on
    # one box and 16 on the next and left one of them the same height it started.
    rim = max(v[2] for v in V if inside(v))
    moved = 0
    for v in V:
        x, y, z = v
        if   x < x0 - 1e-4: hinge, axis = x0, 0
        elif x > x1 + 1e-4: hinge, axis = x1, 0
        elif y < y0 - 1e-4: hinge, axis = y0, 1
        elif y > y1 + 1e-4: hinge, axis = y1, 1
        else: continue
        run = math.hypot(v[axis] - hinge, z - rim)      # the flap's real length, hinge -> tip
        v[axis] = hinge + (-run if v[axis] > hinge else run)   # fold INWARD, over the opening
        v[2] = rim                                              # and flat onto the rim
        moved += 1
    with open(dst, "w") as fh:
        for h in head: fh.write(h + "\n")
        fh.write("# CLOSED variant GENERATED by tools/make_closed_cardboard.py -- the game ships no closed box.\n")
        for v in V: fh.write("v %.6f %.6f %.6f\n" % tuple(v))
        for r in rest: fh.write(r)
    return moved, rim

base = "game/content/objects"
for n in range(4):
    src = os.path.join(base, "Cardboard_%d.obj" % n)
    dst = os.path.join(base, "Cardboard_%d_closed.obj" % n)
    r = close_box(src, dst)
    print("  Cardboard_%d -> _closed.obj : %d flap verts folded onto z=%.4f" % (n, r[0], r[1]) if r else "  Cardboard_%d FAILED" % n)
