#!/usr/bin/env python3
"""Reproduce ANIMAL_MEASUREMENTS.md from the actual skinned rigs (numpy/scipy/Pillow)."""
import json
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.spatial.transform import Rotation, Slerp

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('deer', 'pig', 'cow')


def render_calipers():
    """Manually identified silhouette landmarks in notes/horse_views/*.png.

    Side ruler: about 235 px/m, ground row 681.5. Top axes: about 148 px/m.
    Endpoint uncertainty is about 1-2 pixels; these are NOT six-decimal data.
    This is the source of authored horse dimensions. `measure` below is the
    independent skinned-vertex audit, never Godot's expanded culling bounds.
    """
    rows = {  # back row, body px, leg px, total-height px, body-width px, head L/H/W px
        'deer': (340, 338, 168, 530, 90, (111, 134, 46)),
        'pig': (489, 204, 101, 229, 54, (101, 89, 48)),
        'cow': (312, 338, 163, 400, 135, (126, 120, 77)),
    }
    return {n: dict(withers=(681.5-y)/235, body=body/235, leg=leg/235,
                    height=height/235, width=width/148,
                    head_length=head[0]/235, head_height=head[1]/235, head_width=head[2]/148)
            for n, (y, body, leg, height, width, head) in rows.items()}


def read(name):
    return json.loads((ROOT / f'game/content/{name}_rig.json').read_text())


def matrix(d):
    m = np.eye(4)
    # Godot Xf: Basis(q).Scaled(s) (row scaling).
    m[:3, :3] = np.diag(d['scale']) @ Rotation.from_quat(d['rot']).as_matrix()
    m[:3, 3] = d['pos']
    return m


def sample(keys, time, rotation=False):
    k = np.array(keys)
    t = np.clip(time, k[0, 0], k[-1, 0])
    if rotation:
        return Slerp(k[:, 0], Rotation.from_quat(k[:, 1:]))([t]).as_quat()[0]
    return np.array([np.interp(t, k[:, 0], k[:, i]) for i in range(1, k.shape[1])])


def globals_for(d, clip=None, time=0):
    out = []
    for b in d['bones']:
        local = dict(b)
        if clip:
            for key, keys in d['anims'][clip]['tracks'].get(b['name'], {}).items():
                local[key] = sample(keys, time, key == 'rot')
        out.append((out[b['parent']] if b['parent'] >= 0 else np.eye(4)) @ matrix(local))
    return out


def posed(d, clip=None, time=0):
    g = globals_for(d, clip, time)
    binds = np.array([g[s['bone']] @ matrix(s) for s in d['skin']])
    p = np.c_[d['positions'], np.ones(d['vcount'])]
    slots, w = np.array(d['skin_index']), np.array(d['skin_weight'])
    w = w / w.sum(axis=1)[:, None]
    return sum(np.einsum('nij,nj->ni', binds[slots[:, k]], p) * w[:, k, None]
               for k in range(2))[:, :3]


def owners(d):
    return np.array([d['bones'][d['skin'][slots[int(np.argmax(w))]]['bone']]['name']
                     for slots, w in zip(d['skin_index'], d['skin_weight'])])


def head_core(d, p):
    # Weld positions within the Skull group. The connected component containing
    # the most forward vertex is the muzzle/cranium, excluding eyes/ears/antlers.
    ids, points, adj = {}, {}, {}
    for i in np.where(owners(d) == 'Skull')[0]:
        ids[i] = points.setdefault(tuple(np.round(d['positions'][i], 5)), len(points))
        adj.setdefault(ids[i], set())
    for f in np.array(d['faces']).reshape(-1, 3):
        ii = [ids[i] for i in f if i in ids]
        for i in ii:
            adj[i].update(ii)
    seed = min(ids, key=lambda i: p[i, 0])
    seen, todo = set(), [ids[seed]]
    while todo:
        i = todo.pop()
        if i not in seen:
            seen.add(i)
            todo.extend(adj[i] - seen)
    return p[[i for i, v in ids.items() if v in seen]]


def measure(d):
    p = posed(d)
    own = owners(d)
    spine = p[own == 'Spine']
    front = spine[spine[:, 0] < 0]
    leg = p[own == 'Left_Front']
    return dict(min=p.min(0), max=p.max(0), size=np.ptp(p, axis=0),
                withers=front[:, 1].max(), body=np.ptp(spine[:, 0]),
                width=np.ptp(spine[:, 2]), belly=front[:, 1].min(),
                leg=np.ptp(leg[:, 1]), head=np.ptp(head_core(d, p), axis=0))


def vec(a):
    return '(' + ', '.join(f'{x:.6f}' for x in a) + ')'


def main():
    rigs = {n: read(n) for n in NAMES}
    ms = {n: measure(d) for n, d in rigs.items()}
    lines = ['# Animal measurements', '',
             'Generated by `python3 tools/measure_animals.py`. Units are metres; no retail dimensions or capsule heights were substituted for mesh measurements.', '',
             '## Render measurements — independent calibration', '',
             'Measured and visually inspected with `tools/shot.py animal`, `UG_ANIMALFOOT=0`, `UG_ANIMALYAW=270`, orthographic side views. Screenshots are in `notes/horse_views/`: deer-side.png, pig-side.png, cow-rest-side.png and fleet-top.png. Deer/pig Idle t=0 agrees with rest to sub-pixel precision; cow is explicitly rendered at rest because its Idle Skull rotation differs. No `GetAabb()` result was used.', '',
             'The side captures are 1200×800. The white Y=0 datum is at row ≈681.5 and the 1.0 m tick at ≈446.5: **235 pixels/metre**, independently established by the drawn ruler. A point at row r has Y≈(681.5−r)/235. Pixel readings are reported to 0.01 m, with about ±0.01 m endpoint uncertainty; the six-decimal tables below are the separately reconstructed geometry audit, not six-decimal visual precision.', '',
             '| Animal | Back sample pixel (x,y) | Withers from render m | Body rear/front pixels | Body length m | Front leg top/bottom rows | Leg span m | Full silhouette top/bottom rows | Full height m |',
             '|---|---|---:|---|---:|---|---:|---|---:|',
             '| deer | (600,340) | 1.45 | 431 / 769 | 1.44 | 527 / 695 | 0.71 | 165 / 695 | 2.26 |',
             '| pig | (600,489) | 0.82 | 498 / 702 | 0.87 | 589 / 690 | 0.43 | 461 / 690 | 0.97 |',
             '| cow | (600,312) | 1.57 | 431 / 769 | 1.44 | 532 / 695 | 0.69 | 295 / 695 | 1.70 |', '',
             'Front leg spans include the visible tips below the datum: ≈−0.06 m deer/cow, ≈−0.04 m pig. Ground-to-belly clearance is ≈0.66 / 0.39 / 0.56 m; it is a different landmark from the entire leg mesh. Foot placement remains zero; these are small source-mesh penetrations, not positive foot-lift values.', '',
             'The top capture includes separate 1 m BLUE +X and RED −Z bars. All noses point along −Z after the 270° correction. Its scale is ≈148 pixels/metre: deer body width ≈90 px (0.61 m), antler span ≈216 px (1.46 m); pig ≈54 px (0.36 m); cow ≈135 px (0.91 m). This independently disambiguates length and width.', '',
             '| Animal | Core head side L / H, pixels | Core head top width, pixels | Render head L × W × H, metres |',
             '|---|---|---:|---|',
             '| deer | 111 / 134 | 46 | 0.47 × 0.31 × 0.57 |',
             '| pig | 101 / 89 | 48 | 0.43 × 0.32 × 0.38 |',
             '| cow | 126 / 120 | 77 | 0.54 × 0.52 × 0.51 |', '',
             'Head calipers exclude separate antlers/ears and agree with the reconstructed component bounds below to about 0.01 m. `render_calipers()` retains the pixel readings divided by the ruler calibration; the horse generator derives its dimensions from those readings. The following reconstructed geometry is an independent audit of the instrument, not the source of invented visual precision.', '',
             '## Measurement convention and geometry audit', '',
             '`positions` are stored in mesh bind coordinates. They are **not a Godot world-space AABB**. The extraction path in `tools/deer_rig_extract.py` and `tools/rig_extract.py` stores two weights per vertex and six skin binds for seven skeleton bones. For each vertex this script computes `sum(weight * global_bone_pose[skin[skin_index].bone] * skin_bind * position)`, matching `RiggedCharacter.BuildFrom`. Quaternions are normalized; hierarchy transforms are composed parent first. Local facing is −X, up is +Y, width is Z after skinning.', '',
             'The main tables use the skeleton rest pose, at agent position (0,0,0), without a foot lift. “Withers” is the highest front-half Spine vertex above the terrain plane Y=0; body length/width are the Spine bounds. “Exposed leg” is the Left_Front weighted vertex Y span, not the hip-bone length (this fleet has one bone per leg). Head core is the position-welded Skull component containing the most forward muzzle vertex; separate eyes, ears and deer antlers are excluded. These are reproducible mesh landmarks, not inferred biological measurements.', '',
             '**Origin-at-feet caveat:** the origin is the intended ground plane, but source hoof tips extend below it. Tables retain this measured penetration; they do not add the obsolete 0.70/0.22/0.52 m lifts. Foot-tip-to-withers measurements are listed separately.', '',
             '## Geometry and hierarchy', '',
             '| Animal | Vertices | Triangles | Bones / skin binds | Bone index: name → parent index |',
             '|---|---:|---:|---:|---|']
    for n, d in rigs.items():
        hierarchy = '; '.join(f"{i}: {b['name']} → {b['parent']}" for i, b in enumerate(d['bones']))
        lines.append(f"| {n} | {d['vcount']} | {len(d['faces'])//3} | {len(d['bones'])} / {len(d['skin'])} | {hierarchy} |")
    lines += ['', 'Parent −1 means root. All 3/3 share the same seven names and named parent relationships. Pig swaps Left_Back/Right_Back indices 1 and 2. All three skin lists map slots `[0,1,2,3,4,5]` to bones `[3,4,5,6,1,2]`; slot 4 therefore means Left_Back in deer/cow but Right_Back in pig.', '',
              '## AABB at rest', '',
              '| Animal | Length X | Width Z (incl. antlers) | Height Y | Minimum XYZ | Maximum XYZ | Origin fraction XYZ within AABB |',
              '|---|---:|---:|---:|---|---|---|']
    for n, m in ms.items():
        lines.append(f"| {n} | {m['size'][0]:.6f} | {m['size'][2]:.6f} | {m['size'][1]:.6f} | {vec(m['min'])} | {vec(m['max'])} | {vec(-m['min']/m['size'])} |")
    lines += ['', 'Raw stored coordinates (for auditing the axis conversion):', '',
              '| Animal | Raw minimum XYZ | Raw maximum XYZ |', '|---|---|---|']
    for n, d in rigs.items():
        p = np.array(d['positions'])
        lines.append(f'| {n} | {vec(p.min(0))} | {vec(p.max(0))} |')
    lines += ['', '## Proportions', '',
              '| Animal | Withers above Y=0 | Hoof-tip to withers | Body length | Body width | Exposed front leg | Leg / withers | Leg / total height | Head core L × W × H |',
              '|---|---:|---:|---:|---:|---:|---:|---:|---|']
    for n, m in ms.items():
        lines.append(f"| {n} | {m['withers']:.6f} | {m['withers']-m['min'][1]:.6f} | {m['body']:.6f} | {m['width']:.6f} | {m['leg']:.6f} | {m['leg']/m['withers']:.6f} | {m['leg']/m['size'][1]:.6f} | {vec(m['head'][[0,2,1]])} |")
    lines += ['', '## Texture and capsule', '',
              'Distinct colours count decoded RGBA pixels, including every texel (not an estimated palette size). All alpha values are 255.', '',
              '| Animal | Texture | Pixels | Distinct RGBA | RGB hex: texel count | bodyH | bodyH / rest mesh height | bodyH − withers |',
              '|---|---|---|---:|---|---:|---:|---:|']
    for n, bodyh in zip(NAMES, (1.30, .75, 1.45)):
        im = Image.open(ROOT / f'game/content/objects/Animal_{n.title()}_tex.png').convert('RGBA')
        colors = sorted(im.getcolors(), reverse=True)
        palette = '; '.join('#' + ''.join(f'{x:02X}' for x in c[:3]) + f': {count}' for count, c in colors)
        m = ms[n]
        lines.append(f"| {n} | Animal_{n.title()}_tex.png | {im.width}×{im.height} | {len(colors)} | {palette} | {bodyh:.2f} | {bodyh/m['size'][1]:.6f} | {bodyh-m['withers']:.6f} |")
    lines += ['', '**Flag, all three:** bodyH is lower than both the full height and the measured back. Full-height mismatch is partly intentional (AnimalAgent describes a feet-to-back capsule, excluding the head/antlers), but the capsule also undershoots the back by the amounts above. Existing values are retained. Cow is predominantly greyscale Holstein, but its texture is not strictly B&W: one pink texel and one pure-black texel accompany the 531 light-grey and 491 dark-grey texels.', '',
              '## Animation comparison', '',
              'All 3/3 embed the same seven clip names, durations, 30 fps, named tracks and key counts in their own JSON; there is no external shared animal clip asset. No complete clip is byte-for-byte equal between different animals. Deer and cow share 6/7 bone tracks in every clip (all except Skull); pig shares only the Skeleton track exactly with deer. The naming contract is shared, while species-specific transforms are retained.', '',
              '| Animal | Clips: duration seconds | Keys across all channels per clip, same order |', '|---|---|---|']
    for n, d in rigs.items():
        durations = '; '.join(f"{k} {a['length']:.6f}" for k, a in d['anims'].items())
        counts = ', '.join(str(sum(len(v) for t in a['tracks'].values() for v in t.values())) for a in d['anims'].values())
        lines.append(f'| {n} | {durations} | {counts} |')
    lines += ['', 'Only Startle is non-looping. Rest pose and Idle at t=0 differ in cow Skull orientation; the following actually skinned Idle bounds prevent confusing that change with scaling:', '',
              '| Animal | Idle t=0 minimum XYZ | Idle t=0 maximum XYZ |', '|---|---|---|']
    for n, d in rigs.items():
        p = posed(d, 'Idle')
        lines.append(f'| {n} | {vec(p.min(0))} | {vec(p.max(0))} |')
    lines += ['', 'Fleet distribution: vertices min/median/max **220 / 250 / 329** (mean 266.333); triangles **124 / 148 / 188** (mean 153.333); bones **7 / 7 / 7**; skin binds **6 / 6 / 6**. Textures: two at 2×2, one at 32×32, all with exactly four colours.', '']
    (ROOT / 'notes/ANIMAL_MEASUREMENTS.md').write_text('\n'.join(lines))
    for n, m in ms.items():
        print(n, {k: np.round(v, 6).tolist() for k, v in m.items()})


if __name__ == '__main__':
    main()
